In [51]:
import pandas as pd
import numpy as np

In [83]:
inf_mor = pd.read_csv('../data/cleaned/infant_mortality_with_mean.csv')
air_data = pd.read_csv('../data/cleaned/air_all_years.csv', )

In [84]:
inf_mor

,Location,1999,2000,2001,2002,2003,2004,2005,2006,2007,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Albuquerque,6.900000,6.500000,5.700000,6.900000,4.500000,6.400000,5.100000,5.200000,NaN,...,4.200000,4.500000,5.500000,6.600000,5.700000,5.9,4.900000,7.200000,5.500000,5.600000
1,Atlanta,9.200000,7.800000,7.700000,1.300000,1.100000,NaN,3.100000,7.300000,NaN,...,10.900000,6.700000,9.300000,5.500000,5.500000,7.9,8.400000,6.500000,5.900000,4.600000
2,Austin,5.100000,4.600000,5.300000,4.600000,6.200000,4.900000,5.400000,5.600000,NaN,...,5.500000,4.900000,4.400000,4.500000,4.200000,4.6,3.600000,3.400000,3.700000,3.300000
3,Baltimore,14.100000,11.600000,11.300000,9.900000,12.800000,12.500000,11.200000,12.200000,NaN,...,13.510000,2.000000,10.800000,10.000000,10.200000,10.4,7.700000,8.500000,8.200000,8.600000
4,Boston,7.400000,6.700000,7.200000,6.900000,6.100000,6.200000,5.100000,5.900000,NaN,...,6.700000,3.800000,5.300000,4.900000,4.700000,6.3,5.500000,5.300000,4.700000,4.000000
5,Charlotte,6.500000,8.900000,8.300000,8.600000,7.200000,9.800000,8.800000,7.300000,NaN,...,6.300000,6.000000,6.200000,5.600000,6.500000,6.0,6.200000,7.200000,5.100000,4.900000
6,Chicago,12.200000,10.900000,9.500000,9.000000,10.000000,8.900000,9.100000,7.200000,NaN,...,8.000000,7.500000,7.900000,7.700000,6.600000,7.0,7.800000,6.900000,6.700000,7.200000
7,Cleveland,13.000000,13.200000,11.200000,14.700000,10.000000,14.800000,15.000000,14.000000,NaN,...,14.300000,13.500000,14.100000,13.400000,13.500000,11.3,17.000000,12.200000,13.300000,14.600000
8,Colorado Springs,8.800000,7.800000,6.200000,6.900000,7.200000,8.700000,7.800000,10.000000,NaN,...,7.200000,7.600000,7.100000,5.200000,4.800000,4.1,5.500000,5.400000,5.700000,4.300000
9,Columbus,9.800000,9.900000,9.200000,10.800000,9.800000,8.300000,9.800000,10.000000,NaN,...,7.900000,7.600000,8.900000,8.000000,7.900000,8.8,9.800000,9.300000,8.800000,8.200000
10,Dallas,6.800000,5.400000,6.500000,6.800000,8.100000,6.800000,7.300000,8.500000,NaN,...,8.000000,7.500000,7.500000,7.100000,7.200000,7.2,6.700000,6.000000,7.800000,6.100000
11,Denver,6.200000,6.000000,5.300000,7.100000,7.000000,6.600000,8.800000,5.200000,NaN,...,7.000000,6.100000,4.500000,5.600000,7.300000,4.4,5.500000,4.800000,3.500000,4.400000
12,Detroit,14.600000,14.800000,14.000000,16.700000,16.400000,15.500000,16.000000,13.400000,NaN,...,14.800000,13.500000,12.400000,15.000000,13.400000,10.5,12.800000,12.900000,14.600000,14.300000
13,District of Columbia,15.000000,12.000000,10.600000,11.300000,10.500000,12.000000,14.100000,11.300000,13.1,...,9.800000,7.900000,7.500000,8.000000,6.800000,7.3,8.600000,7.100000,8.100000,6.900000
14,El Paso,5.000000,4.400000,5.000000,3.500000,3.900000,3.700000,5.100000,4.700000,NaN,...,3.900000,3.900000,4.900000,4.500000,4.800000,5.1,4.300000,4.200000,4.800000,3.500000
15,Fresno,6.700000,6.800000,5.900000,8.300000,7.000000,8.000000,7.700000,7.200000,NaN,...,6.100000,7.400000,8.200000,6.200000,9.200000,8.2,8.000000,5.700000,7.800000,7.200000
16,Houston,6.500000,5.100000,5.500000,7.100000,6.900000,7.300000,6.900000,5.900000,NaN,...,6.900000,6.400000,5.500000,6.100000,6.800000,6.1,5.900000,6.000000,6.000000,6.200000
17,Indianapolis,11.000000,9.900000,7.800000,8.500000,9.400000,10.100000,9.800000,9.300000,NaN,...,11.300000,9.700000,9.500000,7.400000,9.200000,8.4,7.900000,8.500000,7.300000,7.900000
18,Jacksonville,10.600000,9.300000,11.300000,9.600000,10.200000,11.300000,12.100000,10.100000,NaN,...,8.800000,8.200000,8.300000,9.300000,9.600000,9.8,8.400000,9.300000,9.000000,10.500000
19,Kansas City,8.900000,7.200000,7.600000,9.800000,8.300000,8.200000,7.300000,9.000000,NaN,...,7.100000,6.200000,5.900000,7.300000,6.000000,6.0,5.600000,6.700000,7.500000,6.400000
20,Las Vegas,4.900000,3.900000,5.700000,5.300000,3.700000,4.300000,3.500000,5.600000,NaN,...,3.300000,3.200000,2.400000,3.700000,3.200000,4.2,4.600000,5.100000,4.300000,4.100000
21,Los Angeles,6.100000,4.900000,5.700000,5.800000,5.500000,5.800000,5.100000,4.800000,NaN,...,5.000000,5.200000,4.900000,4.600000,4.900000,4.5,4.300000,4.200000,4.400000,4.000000
22,Louisville,7.400000,7.000000,5.700000,6.900000,4.900000,5.600000,5.500000,7.100000,NaN,...,7.300000,6.900000,6.700000,7.900000,5.100000,6.6,6.500000,6.100000,6.600000,4.900000
23,Memphis,13.300000,16.100000,14.900000,16.700000,17.300000,14.700000,13.300000,16.000000,NaN,...,14.900000,11.700000,10.700000,11.800000,10.500000,10.3,9.900000,10.100000,11.100000,10.000000
24,Miami,5.200000,5.400000,4.900000,4.700000,5.100000,4.300000,7.900000,3.800000,NaN,...,5.300000,4.700000,5.000000,4.800000,5.200000,5.5,5.800000,6.600000,5.200000,4.500000
25,Milwaukee,10.500000,11.400000,11.500000,12.100000,11.400000,11.900000,11.100000,11.900000,NaN,...,11.100000,9.400000,9.300000,9.600000,11.300000,8.5,9.500000,9.400000,12.300000,10.800000
26,Minneapolis,7.900000,6.200000,5.600000,6.700000,5.500000,6.900000,5.800000,6.900000,NaN,...,4.700000,6.800000,6.500000,5.300000,7.400000,7.2,7.200000,7.000000,5.800000,6.500000
27,Nashville,9.200000,10.200000,8.700000,10.200000,7.400000,6.300000,8.100000,9.300000,NaN,...,7.800000,7.800000,7.600000,7.000000,7.600000,6.5,7.100000,7.300000,7.000000,6.700000
28,New York City,6.700000,6.400000,5.600000,5.900000,6.200000,6.100000,5.600000,5.700000,NaN,...,5.000000,4.600000,4.500000,4.600000,4.200000,4.0,4.100000,3.800000,4.200000,3.500000
29,Oklahoma City,9.300000,12.600000,8.900000,8.700000,10.300000,10.600000,9.300000,7.000000,NaN,...,11.000000,8.100000,7.200000,8.200000,7.900000,7.0,7.400000,8.900000,7.400000,8.100000
30,Omaha,7.900000,8.900000,7.500000,9.800000,7.300000,6.200000,6.500000,7.900000,NaN,...,6.000000,6.500000,6.200000,4.400000,7.800000,5.2,7.000000,7.400000,7.200000,6.700000
31,Philadelphia,12.200000,10.500000,10.500000,10.700000,10.700000,11.200000,12.000000,12.200000,NaN,...,11.100000,10.500000,9.500000,10.000000,9.300000,7.3,8.000000,8.500000,8.300000,8.100000
32,Phoenix,8.000000,6.700000,7.900000,6.600000,6.800000,7.200000,6.700000,6.800000,NaN,...,6.900000,7.000000,7.500000,6.400000,5.600000,6.7,5.400000,6.500000,5.900000,5.700000
33,Portland,5.200000,5.900000,3.200000,4.500000,3.900000,5.300000,5.900000,5.800000,NaN,...,5.200000,5.400000,4.300000,4.800000,4.400000,5.1,5.100000,3.700000,4.100000,3.300000
34,Sacramento,6.500000,6.600000,7.200000,7.100000,5.900000,5.700000,5.900000,6.200000,NaN,...,7.000000,5.200000,6.300000,6.000000,5.500000,5.2,5.700000,4.800000,5.500000,5.900000
35,San Antonio,6.500000,4.900000,5.700000,7.300000,7.500000,6.300000,6.600000,6.500000,NaN,...,5.800000,6.700000,5.100000,7.000000,6.500000,5.4,6.800000,6.700000,6.800000,7.300000
36,San Diego,5.400000,6.600000,6.200000,4.200000,4.500000,5.100000,4.500000,5.000000,NaN,...,4.800000,4.900000,3.800000,4.600000,4.200000,3.6,3.400000,4.000000,3.800000,4.500000
37,San Francisco,3.800000,4.000000,3.800000,4.600000,3.100000,3.600000,3.600000,3.100000,NaN,...,3.700000,3.400000,NaN,3.200000,3.600000,2.5,3.600000,NaN,2.500000,3.700000
38,San Jose,4.700000,4.800000,4.200000,3.600000,4.000000,4.500000,3.800000,3.900000,NaN,...,4.100000,3.300000,3.000000,3.100000,4.000000,3.3,3.500000,3.300000,3.300000,4.200000
39,San Juan,14.100000,9.900000,10.100000,12.800000,11.300000,NaN,NaN,NaN,NaN,...,7.700000,9.500000,8.700000,9.800000,9.500000,9.3,9.900000,10.200000,11.100000,NaN
40,Seattle,6.500000,4.600000,4.800000,4.000000,5.600000,5.200000,4.900000,3.500000,NaN,...,3.900000,3.500000,3.700000,5.400000,5.000000,3.7,3.300000,3.600000,3.300000,3.900000
41,Tucson,5.100000,5.500000,7.400000,6.900000,6.600000,7.300000,8.700000,7.200000,NaN,...,5.800000,5.100000,4.200000,4.900000,4.200000,5.5,5.000000,5.100000,4.100000,5.600000
42,Tulsa,8.200000,9.600000,8.200000,10.100000,8.200000,6.900000,8.900000,8.900000,NaN,...,8.400000,7.300000,6.900000,11.200000,8.300000,9.4,7.100000,10.200000,8.700000,7.600000
43,Virginia Beach,9.400000,6.000000,7.100000,7.200000,6.800000,7.800000,7.800000,10.300000,NaN,...,5.500000,6.800000,6.900000,6.100000,5.800000,4.6,5.600000,4.900000,4.600000,5.700000
44,Wichita,NaN,NaN,NaN,NaN,NaN,8.800000,10.600000,7.700000,NaN,...,9.300000,6.900000,7.300000,8.800000,8.900000,6.1,6.600000,8.300000,6.900000,8.100000
45,Infant Mortality Mean,8.370455,7.895455,7.547727,7.970455,7.547727,7.851163,7.888636,7.781818,13.1,...,7.529111,6.695556,6.861364,6.913333,6.884444,6.5,6.722222,6.790909,6.631111,6.411364

In [85]:
inf_mor.set_index('Location', inplace = True)

In [86]:
inf_mor

,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
Location,,,,,,,,,,,,,,,,,,,,
Albuquerque,6.900000,6.500000,5.700000,6.900000,4.500000,6.400000,5.100000,5.200000,NaN,NaN,4.200000,4.500000,5.500000,6.600000,5.700000,5.9,4.900000,7.200000,5.500000,5.600000
Atlanta,9.200000,7.800000,7.700000,1.300000,1.100000,NaN,3.100000,7.300000,NaN,NaN,10.900000,6.700000,9.300000,5.500000,5.500000,7.9,8.400000,6.500000,5.900000,4.600000
Austin,5.100000,4.600000,5.300000,4.600000,6.200000,4.900000,5.400000,5.600000,NaN,NaN,5.500000,4.900000,4.400000,4.500000,4.200000,4.6,3.600000,3.400000,3.700000,3.300000
Baltimore,14.100000,11.600000,11.300000,9.900000,12.800000,12.500000,11.200000,12.200000,NaN,NaN,13.510000,2.000000,10.800000,10.000000,10.200000,10.4,7.700000,8.500000,8.200000,8.600000
Boston,7.400000,6.700000,7.200000,6.900000,6.100000,6.200000,5.100000,5.900000,NaN,NaN,6.700000,3.800000,5.300000,4.900000,4.700000,6.3,5.500000,5.300000,4.700000,4.000000
Charlotte,6.500000,8.900000,8.300000,8.600000,7.200000,9.800000,8.800000,7.300000,NaN,NaN,6.300000,6.000000,6.200000,5.600000,6.500000,6.0,6.200000,7.200000,5.100000,4.900000
Chicago,12.200000,10.900000,9.500000,9.000000,10.000000,8.900000,9.100000,7.200000,NaN,NaN,8.000000,7.500000,7.900000,7.700000,6.600000,7.0,7.800000,6.900000,6.700000,7.200000
Cleveland,13.000000,13.200000,11.200000,14.700000,10.000000,14.800000,15.000000,14.000000,NaN,NaN,14.300000,13.500000,14.100000,13.400000,13.500000,11.3,17.000000,12.200000,13.300000,14.600000
Colorado Springs,8.800000,7.800000,6.200000,6.900000,7.200000,8.700000,7.800000,10.000000,NaN,NaN,7.200000,7.600000,7.100000,5.200000,4.800000,4.1,5.500000,5.400000,5.700000,4.300000
Columbus,9.800000,9.900000,9.200000,10.800000,9.800000,8.300000,9.800000,10.000000,NaN,NaN,7.900000,7.600000,8.900000,8.000000,7.900000,8.8,9.800000,9.300000,8.800000,8.200000
Dallas,6.800000,5.400000,6.500000,6.800000,8.100000,6.800000,7.300000,8.500000,NaN,NaN,8.000000,7.500000,7.500000,7.100000,7.200000,7.2,6.700000,6.000000,7.800000,6.100000
Denver,6.200000,6.000000,5.300000,7.100000,7.000000,6.600000,8.800000,5.200000,NaN,NaN,7.000000,6.100000,4.500000,5.600000,7.300000,4.4,5.500000,4.800000,3.500000,4.400000
Detroit,14.600000,14.800000,14.000000,16.700000,16.400000,15.500000,16.000000,13.400000,NaN,NaN,14.800000,13.500000,12.400000,15.000000,13.400000,10.5,12.800000,12.900000,14.600000,14.300000
District of Columbia,15.000000,12.000000,10.600000,11.300000,10.500000,12.000000,14.100000,11.300000,13.1,10.8,9.800000,7.900000,7.500000,8.000000,6.800000,7.3,8.600000,7.100000,8.100000,6.900000
El Paso,5.000000,4.400000,5.000000,3.500000,3.900000,3.700000,5.100000,4.700000,NaN,NaN,3.900000,3.900000,4.900000,4.500000,4.800000,5.1,4.300000,4.200000,4.800000,3.500000
Fresno,6.700000,6.800000,5.900000,8.300000,7.000000,8.000000,7.700000,7.200000,NaN,NaN,6.100000,7.400000,8.200000,6.200000,9.200000,8.2,8.000000,5.700000,7.800000,7.200000
Houston,6.500000,5.100000,5.500000,7.100000,6.900000,7.300000,6.900000,5.900000,NaN,NaN,6.900000,6.400000,5.500000,6.100000,6.800000,6.1,5.900000,6.000000,6.000000,6.200000
Indianapolis,11.000000,9.900000,7.800000,8.500000,9.400000,10.100000,9.800000,9.300000,NaN,NaN,11.300000,9.700000,9.500000,7.400000,9.200000,8.4,7.900000,8.500000,7.300000,7.900000
Jacksonville,10.600000,9.300000,11.300000,9.600000,10.200000,11.300000,12.100000,10.100000,NaN,NaN,8.800000,8.200000,8.300000,9.300000,9.600000,9.8,8.400000,9.300000,9.000000,10.500000
Kansas City,8.900000,7.200000,7.600000,9.800000,8.300000,8.200000,7.300000,9.000000,NaN,NaN,7.100000,6.200000,5.900000,7.300000,6.000000,6.0,5.600000,6.700000,7.500000,6.400000
Las Vegas,4.900000,3.900000,5.700000,5.300000,3.700000,4.300000,3.500000,5.600000,NaN,NaN,3.300000,3.200000,2.400000,3.700000,3.200000,4.2,4.600000,5.100000,4.300000,4.100000
Los Angeles,6.100000,4.900000,5.700000,5.800000,5.500000,5.800000,5.100000,4.800000,NaN,NaN,5.000000,5.200000,4.900000,4.600000,4.900000,4.5,4.300000,4.200000,4.400000,4.000000
Louisville,7.400000,7.000000,5.700000,6.900000,4.900000,5.600000,5.500000,7.100000,NaN,NaN,7.300000,6.900000,6.700000,7.900000,5.100000,6.6,6.500000,6.100000,6.600000,4.900000
Memphis,13.300000,16.100000,14.900000,16.700000,17.300000,14.700000,13.300000,16.000000,NaN,NaN,14.900000,11.700000,10.700000,11.800000,10.500000,10.3,9.900000,10.100000,11.100000,10.000000
Miami,5.200000,5.400000,4.900000,4.700000,5.100000,4.300000,7.900000,3.800000,NaN,NaN,5.300000,4.700000,5.000000,4.800000,5.200000,5.5,5.800000,6.600000,5.200000,4.500000
Milwaukee,10.500000,11.400000,11.500000,12.100000,11.400000,11.900000,11.100000,11.900000,NaN,NaN,11.100000,9.400000,9.300000,9.600000,11.300000,8.5,9.500000,9.400000,12.300000,10.800000
Minneapolis,7.900000,6.200000,5.600000,6.700000,5.500000,6.900000,5.800000,6.900000,NaN,NaN,4.700000,6.800000,6.500000,5.300000,7.400000,7.2,7.200000,7.000000,5.800000,6.500000
Nashville,9.200000,10.200000,8.700000,10.200000,7.400000,6.300000,8.100000,9.300000,NaN,NaN,7.800000,7.800000,7.600000,7.000000,7.600000,6.5,7.100000,7.300000,7.000000,6.700000
New York City,6.700000,6.400000,5.600000,5.900000,6.200000,6.100000,5.600000,5.700000,NaN,NaN,5.000000,4.600000,4.500000,4.600000,4.200000,4.0,4.100000,3.800000,4.200000,3.500000
Oklahoma City,9.300000,12.600000,8.900000,8.700000,10.300000,10.600000,9.300000,7.000000,NaN,NaN,11.000000,8.100000,7.200000,8.200000,7.900000,7.0,7.400000,8.900000,7.400000,8.100000
Omaha,7.900000,8.900000,7.500000,9.800000,7.300000,6.200000,6.500000,7.900000,NaN,NaN,6.000000,6.500000,6.200000,4.400000,7.800000,5.2,7.000000,7.400000,7.200000,6.700000
Philadelphia,12.200000,10.500000,10.500000,10.700000,10.700000,11.200000,12.000000,12.200000,NaN,NaN,11.100000,10.500000,9.500000,10.000000,9.300000,7.3,8.000000,8.500000,8.300000,8.100000
Phoenix,8.000000,6.700000,7.900000,6.600000,6.800000,7.200000,6.700000,6.800000,NaN,NaN,6.900000,7.000000,7.500000,6.400000,5.600000,6.7,5.400000,6.500000,5.900000,5.700000
Portland,5.200000,5.900000,3.200000,4.500000,3.900000,5.300000,5.900000,5.800000,NaN,NaN,5.200000,5.400000,4.300000,4.800000,4.400000,5.1,5.100000,3.700000,4.100000,3.300000
Sacramento,6.500000,6.600000,7.200000,7.100000,5.900000,5.700000,5.900000,6.200000,NaN,NaN,7.000000,5.200000,6.300000,6.000000,5.500000,5.2,5.700000,4.800000,5.500000,5.900000
San Antonio,6.500000,4.900000,5.700000,7.300000,7.500000,6.300000,6.600000,6.500000,NaN,NaN,5.800000,6.700000,5.100000,7.000000,6.500000,5.4,6.800000,6.700000,6.800000,7.300000
San Diego,5.400000,6.600000,6.200000,4.200000,4.500000,5.100000,4.500000,5.000000,NaN,NaN,4.800000,4.900000,3.800000,4.600000,4.200000,3.6,3.400000,4.000000,3.800000,4.500000
San Francisco,3.800000,4.000000,3.800000,4.600000,3.100000,3.600000,3.600000,3.100000,NaN,NaN,3.700000,3.400000,NaN,3.200000,3.600000,2.5,3.600000,NaN,2.500000,3.700000
San Jose,4.700000,4.800000,4.200000,3.600000,4.000000,4.500000,3.800000,3.900000,NaN,NaN,4.100000,3.300000,3.000000,3.100000,4.000000,3.3,3.500000,3.300000,3.300000,4.200000
San Juan,14.100000,9.900000,10.100000,12.800000,11.300000,NaN,NaN,NaN,NaN,NaN,7.700000,9.500000,8.700000,9.800000,9.500000,9.3,9.900000,10.200000,11.100000,NaN
Seattle,6.500000,4.600000,4.800000,4.000000,5.600000,5.200000,4.900000,3.500000,NaN,NaN,3.900000,3.500000,3.700000,5.400000,5.000000,3.7,3.300000,3.600000,3.300000,3.900000
Tucson,5.100000,5.500000,7.400000,6.900000,6.600000,7.300000,8.700000,7.200000,NaN,NaN,5.800000,5.100000,4.200000,4.900000,4.200000,5.5,5.000000,5.100000,4.100000,5.600000
Tulsa,8.200000,9.600000,8.200000,10.100000,8.200000,6.900000,8.900000,8.900000,NaN,NaN,8.400000,7.300000,6.900000,11.200000,8.300000,9.4,7.100000,10.200000,8.700000,7.600000
Virginia Beach,9.400000,6.000000,7.100000,7.200000,6.800000,7.800000,7.800000,10.300000,NaN,NaN,5.500000,6.800000,6.900000,6.100000,5.800000,4.6,5.600000,4.900000,4.600000,5.700000
Wichita,NaN,NaN,NaN,NaN,NaN,8.800000,10.600000,7.700000,NaN,NaN,9.300000,6.900000,7.300000,8.800000,8.900000,6.1,6.600000,8.300000,6.900000,8.100000
Infant Mortality Mean,8.370455,7.895455,7.547727,7.970455,7.547727,7.851163,7.888636,7.781818,13.1,10.8,7.529111,6.695556,6.861364,6.913333,6.884444,6.5,6.722222,6.790909,6.631111,6.411364

In [87]:
inf_mor.loc['Infant Mortality First Quartile'] = inf_mor.loc['Albuquerque':'Wichita'].quantile(.25)

In [88]:
inf_mor

,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
Location,,,,,,,,,,,,,,,,,,,,
Albuquerque,6.900000,6.500000,5.700000,6.900000,4.500000,6.400000,5.100000,5.200000,NaN,NaN,4.200000,4.500000,5.500000,6.600000,5.700000,5.9,4.900000,7.200000,5.500000,5.600000
Atlanta,9.200000,7.800000,7.700000,1.300000,1.100000,NaN,3.100000,7.300000,NaN,NaN,10.900000,6.700000,9.300000,5.500000,5.500000,7.9,8.400000,6.500000,5.900000,4.600000
Austin,5.100000,4.600000,5.300000,4.600000,6.200000,4.900000,5.400000,5.600000,NaN,NaN,5.500000,4.900000,4.400000,4.500000,4.200000,4.6,3.600000,3.400000,3.700000,3.300000
Baltimore,14.100000,11.600000,11.300000,9.900000,12.800000,12.500000,11.200000,12.200000,NaN,NaN,13.510000,2.000000,10.800000,10.000000,10.200000,10.4,7.700000,8.500000,8.200000,8.600000
Boston,7.400000,6.700000,7.200000,6.900000,6.100000,6.200000,5.100000,5.900000,NaN,NaN,6.700000,3.800000,5.300000,4.900000,4.700000,6.3,5.500000,5.300000,4.700000,4.000000
Charlotte,6.500000,8.900000,8.300000,8.600000,7.200000,9.800000,8.800000,7.300000,NaN,NaN,6.300000,6.000000,6.200000,5.600000,6.500000,6.0,6.200000,7.200000,5.100000,4.900000
Chicago,12.200000,10.900000,9.500000,9.000000,10.000000,8.900000,9.100000,7.200000,NaN,NaN,8.000000,7.500000,7.900000,7.700000,6.600000,7.0,7.800000,6.900000,6.700000,7.200000
Cleveland,13.000000,13.200000,11.200000,14.700000,10.000000,14.800000,15.000000,14.000000,NaN,NaN,14.300000,13.500000,14.100000,13.400000,13.500000,11.3,17.000000,12.200000,13.300000,14.600000
Colorado Springs,8.800000,7.800000,6.200000,6.900000,7.200000,8.700000,7.800000,10.000000,NaN,NaN,7.200000,7.600000,7.100000,5.200000,4.800000,4.1,5.500000,5.400000,5.700000,4.300000
Columbus,9.800000,9.900000,9.200000,10.800000,9.800000,8.300000,9.800000,10.000000,NaN,NaN,7.900000,7.600000,8.900000,8.000000,7.900000,8.8,9.800000,9.300000,8.800000,8.200000
Dallas,6.800000,5.400000,6.500000,6.800000,8.100000,6.800000,7.300000,8.500000,NaN,NaN,8.000000,7.500000,7.500000,7.100000,7.200000,7.2,6.700000,6.000000,7.800000,6.100000
Denver,6.200000,6.000000,5.300000,7.100000,7.000000,6.600000,8.800000,5.200000,NaN,NaN,7.000000,6.100000,4.500000,5.600000,7.300000,4.4,5.500000,4.800000,3.500000,4.400000
Detroit,14.600000,14.800000,14.000000,16.700000,16.400000,15.500000,16.000000,13.400000,NaN,NaN,14.800000,13.500000,12.400000,15.000000,13.400000,10.5,12.800000,12.900000,14.600000,14.300000
District of Columbia,15.000000,12.000000,10.600000,11.300000,10.500000,12.000000,14.100000,11.300000,13.1,10.8,9.800000,7.900000,7.500000,8.000000,6.800000,7.3,8.600000,7.100000,8.100000,6.900000
El Paso,5.000000,4.400000,5.000000,3.500000,3.900000,3.700000,5.100000,4.700000,NaN,NaN,3.900000,3.900000,4.900000,4.500000,4.800000,5.1,4.300000,4.200000,4.800000,3.500000
Fresno,6.700000,6.800000,5.900000,8.300000,7.000000,8.000000,7.700000,7.200000,NaN,NaN,6.100000,7.400000,8.200000,6.200000,9.200000,8.2,8.000000,5.700000,7.800000,7.200000
Houston,6.500000,5.100000,5.500000,7.100000,6.900000,7.300000,6.900000,5.900000,NaN,NaN,6.900000,6.400000,5.500000,6.100000,6.800000,6.1,5.900000,6.000000,6.000000,6.200000
Indianapolis,11.000000,9.900000,7.800000,8.500000,9.400000,10.100000,9.800000,9.300000,NaN,NaN,11.300000,9.700000,9.500000,7.400000,9.200000,8.4,7.900000,8.500000,7.300000,7.900000
Jacksonville,10.600000,9.300000,11.300000,9.600000,10.200000,11.300000,12.100000,10.100000,NaN,NaN,8.800000,8.200000,8.300000,9.300000,9.600000,9.8,8.400000,9.300000,9.000000,10.500000
Kansas City,8.900000,7.200000,7.600000,9.800000,8.300000,8.200000,7.300000,9.000000,NaN,NaN,7.100000,6.200000,5.900000,7.300000,6.000000,6.0,5.600000,6.700000,7.500000,6.400000
Las Vegas,4.900000,3.900000,5.700000,5.300000,3.700000,4.300000,3.500000,5.600000,NaN,NaN,3.300000,3.200000,2.400000,3.700000,3.200000,4.2,4.600000,5.100000,4.300000,4.100000
Los Angeles,6.100000,4.900000,5.700000,5.800000,5.500000,5.800000,5.100000,4.800000,NaN,NaN,5.000000,5.200000,4.900000,4.600000,4.900000,4.5,4.300000,4.200000,4.400000,4.000000
Louisville,7.400000,7.000000,5.700000,6.900000,4.900000,5.600000,5.500000,7.100000,NaN,NaN,7.300000,6.900000,6.700000,7.900000,5.100000,6.6,6.500000,6.100000,6.600000,4.900000
Memphis,13.300000,16.100000,14.900000,16.700000,17.300000,14.700000,13.300000,16.000000,NaN,NaN,14.900000,11.700000,10.700000,11.800000,10.500000,10.3,9.900000,10.100000,11.100000,10.000000
Miami,5.200000,5.400000,4.900000,4.700000,5.100000,4.300000,7.900000,3.800000,NaN,NaN,5.300000,4.700000,5.000000,4.800000,5.200000,5.5,5.800000,6.600000,5.200000,4.500000
Milwaukee,10.500000,11.400000,11.500000,12.100000,11.400000,11.900000,11.100000,11.900000,NaN,NaN,11.100000,9.400000,9.300000,9.600000,11.300000,8.5,9.500000,9.400000,12.300000,10.800000
Minneapolis,7.900000,6.200000,5.600000,6.700000,5.500000,6.900000,5.800000,6.900000,NaN,NaN,4.700000,6.800000,6.500000,5.300000,7.400000,7.2,7.200000,7.000000,5.800000,6.500000
Nashville,9.200000,10.200000,8.700000,10.200000,7.400000,6.300000,8.100000,9.300000,NaN,NaN,7.800000,7.800000,7.600000,7.000000,7.600000,6.5,7.100000,7.300000,7.000000,6.700000
New York City,6.700000,6.400000,5.600000,5.900000,6.200000,6.100000,5.600000,5.700000,NaN,NaN,5.000000,4.600000,4.500000,4.600000,4.200000,4.0,4.100000,3.800000,4.200000,3.500000
Oklahoma City,9.300000,12.600000,8.900000,8.700000,10.300000,10.600000,9.300000,7.000000,NaN,NaN,11.000000,8.100000,7.200000,8.200000,7.900000,7.0,7.400000,8.900000,7.400000,8.100000
Omaha,7.900000,8.900000,7.500000,9.800000,7.300000,6.200000,6.500000,7.900000,NaN,NaN,6.000000,6.500000,6.200000,4.400000,7.800000,5.2,7.000000,7.400000,7.200000,6.700000
Philadelphia,12.200000,10.500000,10.500000,10.700000,10.700000,11.200000,12.000000,12.200000,NaN,NaN,11.100000,10.500000,9.500000,10.000000,9.300000,7.3,8.000000,8.500000,8.300000,8.100000
Phoenix,8.000000,6.700000,7.900000,6.600000,6.800000,7.200000,6.700000,6.800000,NaN,NaN,6.900000,7.000000,7.500000,6.400000,5.600000,6.7,5.400000,6.500000,5.900000,5.700000
Portland,5.200000,5.900000,3.200000,4.500000,3.900000,5.300000,5.900000,5.800000,NaN,NaN,5.200000,5.400000,4.300000,4.800000,4.400000,5.1,5.100000,3.700000,4.100000,3.300000
Sacramento,6.500000,6.600000,7.200000,7.100000,5.900000,5.700000,5.900000,6.200000,NaN,NaN,7.000000,5.200000,6.300000,6.000000,5.500000,5.2,5.700000,4.800000,5.500000,5.900000
San Antonio,6.500000,4.900000,5.700000,7.300000,7.500000,6.300000,6.600000,6.500000,NaN,NaN,5.800000,6.700000,5.100000,7.000000,6.500000,5.4,6.800000,6.700000,6.800000,7.300000
San Diego,5.400000,6.600000,6.200000,4.200000,4.500000,5.100000,4.500000,5.000000,NaN,NaN,4.800000,4.900000,3.800000,4.600000,4.200000,3.6,3.400000,4.000000,3.800000,4.500000
San Francisco,3.800000,4.000000,3.800000,4.600000,3.100000,3.600000,3.600000,3.100000,NaN,NaN,3.700000,3.400000,NaN,3.200000,3.600000,2.5,3.600000,NaN,2.500000,3.700000
San Jose,4.700000,4.800000,4.200000,3.600000,4.000000,4.500000,3.800000,3.900000,NaN,NaN,4.100000,3.300000,3.000000,3.100000,4.000000,3.3,3.500000,3.300000,3.300000,4.200000
San Juan,14.100000,9.900000,10.100000,12.800000,11.300000,NaN,NaN,NaN,NaN,NaN,7.700000,9.500000,8.700000,9.800000,9.500000,9.3,9.900000,10.200000,11.100000,NaN
Seattle,6.500000,4.600000,4.800000,4.000000,5.600000,5.200000,4.900000,3.500000,NaN,NaN,3.900000,3.500000,3.700000,5.400000,5.000000,3.7,3.300000,3.600000,3.300000,3.900000
Tucson,5.100000,5.500000,7.400000,6.900000,6.600000,7.300000,8.700000,7.200000,NaN,NaN,5.800000,5.100000,4.200000,4.900000,4.200000,5.5,5.000000,5.100000,4.100000,5.600000
Tulsa,8.200000,9.600000,8.200000,10.100000,8.200000,6.900000,8.900000,8.900000,NaN,NaN,8.400000,7.300000,6.900000,11.200000,8.300000,9.4,7.100000,10.200000,8.700000,7.600000
Virginia Beach,9.400000,6.000000,7.100000,7.200000,6.800000,7.800000,7.800000,10.300000,NaN,NaN,5.500000,6.800000,6.900000,6.100000,5.800000,4.6,5.600000,4.900000,4.600000,5.700000
Wichita,NaN,NaN,NaN,NaN,NaN,8.800000,10.600000,7.700000,NaN,NaN,9.300000,6.900000,7.300000,8.800000,8.900000,6.1,6.600000,8.300000,6.900000,8.100000
Infant Mortality Mean,8.370455,7.895455,7.547727,7.970455,7.547727,7.851163,7.888636,7.781818,13.1,10.8,7.529111,6.695556,6.861364,6.913333,6.884444,6.5,6.722222,6.790909,6.631111,6.411364
Infant Mortality First Quartile,6.425000,5.475000,5.675000,5.875000,5.500000,5.750000,5.475000,5.675000,13.1,10.8,5.300000,4.900000,4.975000,4.900000,4.900000,5.1,5.100000,5.050000,4.600000,4.375000

In [89]:
inf_mor.loc['Infant Mortality Median'] = inf_mor.loc['Albuquerque':'Wichita'].median()
inf_mor.loc['Infant Mortality Third Quartile'] = inf_mor.loc['Albuquerque':'Wichita'].quantile(.75)

In [90]:
inf_mor

,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
Location,,,,,,,,,,,,,,,,,,,,
Albuquerque,6.900000,6.500000,5.700000,6.900000,4.500000,6.400000,5.100000,5.200000,NaN,NaN,4.200000,4.500000,5.500000,6.600000,5.700000,5.9,4.900000,7.200000,5.500000,5.600000
Atlanta,9.200000,7.800000,7.700000,1.300000,1.100000,NaN,3.100000,7.300000,NaN,NaN,10.900000,6.700000,9.300000,5.500000,5.500000,7.9,8.400000,6.500000,5.900000,4.600000
Austin,5.100000,4.600000,5.300000,4.600000,6.200000,4.900000,5.400000,5.600000,NaN,NaN,5.500000,4.900000,4.400000,4.500000,4.200000,4.6,3.600000,3.400000,3.700000,3.300000
Baltimore,14.100000,11.600000,11.300000,9.900000,12.800000,12.500000,11.200000,12.200000,NaN,NaN,13.510000,2.000000,10.800000,10.000000,10.200000,10.4,7.700000,8.500000,8.200000,8.600000
Boston,7.400000,6.700000,7.200000,6.900000,6.100000,6.200000,5.100000,5.900000,NaN,NaN,6.700000,3.800000,5.300000,4.900000,4.700000,6.3,5.500000,5.300000,4.700000,4.000000
Charlotte,6.500000,8.900000,8.300000,8.600000,7.200000,9.800000,8.800000,7.300000,NaN,NaN,6.300000,6.000000,6.200000,5.600000,6.500000,6.0,6.200000,7.200000,5.100000,4.900000
Chicago,12.200000,10.900000,9.500000,9.000000,10.000000,8.900000,9.100000,7.200000,NaN,NaN,8.000000,7.500000,7.900000,7.700000,6.600000,7.0,7.800000,6.900000,6.700000,7.200000
Cleveland,13.000000,13.200000,11.200000,14.700000,10.000000,14.800000,15.000000,14.000000,NaN,NaN,14.300000,13.500000,14.100000,13.400000,13.500000,11.3,17.000000,12.200000,13.300000,14.600000
Colorado Springs,8.800000,7.800000,6.200000,6.900000,7.200000,8.700000,7.800000,10.000000,NaN,NaN,7.200000,7.600000,7.100000,5.200000,4.800000,4.1,5.500000,5.400000,5.700000,4.300000
Columbus,9.800000,9.900000,9.200000,10.800000,9.800000,8.300000,9.800000,10.000000,NaN,NaN,7.900000,7.600000,8.900000,8.000000,7.900000,8.8,9.800000,9.300000,8.800000,8.200000
Dallas,6.800000,5.400000,6.500000,6.800000,8.100000,6.800000,7.300000,8.500000,NaN,NaN,8.000000,7.500000,7.500000,7.100000,7.200000,7.2,6.700000,6.000000,7.800000,6.100000
Denver,6.200000,6.000000,5.300000,7.100000,7.000000,6.600000,8.800000,5.200000,NaN,NaN,7.000000,6.100000,4.500000,5.600000,7.300000,4.4,5.500000,4.800000,3.500000,4.400000
Detroit,14.600000,14.800000,14.000000,16.700000,16.400000,15.500000,16.000000,13.400000,NaN,NaN,14.800000,13.500000,12.400000,15.000000,13.400000,10.5,12.800000,12.900000,14.600000,14.300000
District of Columbia,15.000000,12.000000,10.600000,11.300000,10.500000,12.000000,14.100000,11.300000,13.1,10.8,9.800000,7.900000,7.500000,8.000000,6.800000,7.3,8.600000,7.100000,8.100000,6.900000
El Paso,5.000000,4.400000,5.000000,3.500000,3.900000,3.700000,5.100000,4.700000,NaN,NaN,3.900000,3.900000,4.900000,4.500000,4.800000,5.1,4.300000,4.200000,4.800000,3.500000
Fresno,6.700000,6.800000,5.900000,8.300000,7.000000,8.000000,7.700000,7.200000,NaN,NaN,6.100000,7.400000,8.200000,6.200000,9.200000,8.2,8.000000,5.700000,7.800000,7.200000
Houston,6.500000,5.100000,5.500000,7.100000,6.900000,7.300000,6.900000,5.900000,NaN,NaN,6.900000,6.400000,5.500000,6.100000,6.800000,6.1,5.900000,6.000000,6.000000,6.200000
Indianapolis,11.000000,9.900000,7.800000,8.500000,9.400000,10.100000,9.800000,9.300000,NaN,NaN,11.300000,9.700000,9.500000,7.400000,9.200000,8.4,7.900000,8.500000,7.300000,7.900000
Jacksonville,10.600000,9.300000,11.300000,9.600000,10.200000,11.300000,12.100000,10.100000,NaN,NaN,8.800000,8.200000,8.300000,9.300000,9.600000,9.8,8.400000,9.300000,9.000000,10.500000
Kansas City,8.900000,7.200000,7.600000,9.800000,8.300000,8.200000,7.300000,9.000000,NaN,NaN,7.100000,6.200000,5.900000,7.300000,6.000000,6.0,5.600000,6.700000,7.500000,6.400000
Las Vegas,4.900000,3.900000,5.700000,5.300000,3.700000,4.300000,3.500000,5.600000,NaN,NaN,3.300000,3.200000,2.400000,3.700000,3.200000,4.2,4.600000,5.100000,4.300000,4.100000
Los Angeles,6.100000,4.900000,5.700000,5.800000,5.500000,5.800000,5.100000,4.800000,NaN,NaN,5.000000,5.200000,4.900000,4.600000,4.900000,4.5,4.300000,4.200000,4.400000,4.000000
Louisville,7.400000,7.000000,5.700000,6.900000,4.900000,5.600000,5.500000,7.100000,NaN,NaN,7.300000,6.900000,6.700000,7.900000,5.100000,6.6,6.500000,6.100000,6.600000,4.900000
Memphis,13.300000,16.100000,14.900000,16.700000,17.300000,14.700000,13.300000,16.000000,NaN,NaN,14.900000,11.700000,10.700000,11.800000,10.500000,10.3,9.900000,10.100000,11.100000,10.000000
Miami,5.200000,5.400000,4.900000,4.700000,5.100000,4.300000,7.900000,3.800000,NaN,NaN,5.300000,4.700000,5.000000,4.800000,5.200000,5.5,5.800000,6.600000,5.200000,4.500000
Milwaukee,10.500000,11.400000,11.500000,12.100000,11.400000,11.900000,11.100000,11.900000,NaN,NaN,11.100000,9.400000,9.300000,9.600000,11.300000,8.5,9.500000,9.400000,12.300000,10.800000
Minneapolis,7.900000,6.200000,5.600000,6.700000,5.500000,6.900000,5.800000,6.900000,NaN,NaN,4.700000,6.800000,6.500000,5.300000,7.400000,7.2,7.200000,7.000000,5.800000,6.500000
Nashville,9.200000,10.200000,8.700000,10.200000,7.400000,6.300000,8.100000,9.300000,NaN,NaN,7.800000,7.800000,7.600000,7.000000,7.600000,6.5,7.100000,7.300000,7.000000,6.700000
New York City,6.700000,6.400000,5.600000,5.900000,6.200000,6.100000,5.600000,5.700000,NaN,NaN,5.000000,4.600000,4.500000,4.600000,4.200000,4.0,4.100000,3.800000,4.200000,3.500000
Oklahoma City,9.300000,12.600000,8.900000,8.700000,10.300000,10.600000,9.300000,7.000000,NaN,NaN,11.000000,8.100000,7.200000,8.200000,7.900000,7.0,7.400000,8.900000,7.400000,8.100000
Omaha,7.900000,8.900000,7.500000,9.800000,7.300000,6.200000,6.500000,7.900000,NaN,NaN,6.000000,6.500000,6.200000,4.400000,7.800000,5.2,7.000000,7.400000,7.200000,6.700000
Philadelphia,12.200000,10.500000,10.500000,10.700000,10.700000,11.200000,12.000000,12.200000,NaN,NaN,11.100000,10.500000,9.500000,10.000000,9.300000,7.3,8.000000,8.500000,8.300000,8.100000
Phoenix,8.000000,6.700000,7.900000,6.600000,6.800000,7.200000,6.700000,6.800000,NaN,NaN,6.900000,7.000000,7.500000,6.400000,5.600000,6.7,5.400000,6.500000,5.900000,5.700000
Portland,5.200000,5.900000,3.200000,4.500000,3.900000,5.300000,5.900000,5.800000,NaN,NaN,5.200000,5.400000,4.300000,4.800000,4.400000,5.1,5.100000,3.700000,4.100000,3.300000
Sacramento,6.500000,6.600000,7.200000,7.100000,5.900000,5.700000,5.900000,6.200000,NaN,NaN,7.000000,5.200000,6.300000,6.000000,5.500000,5.2,5.700000,4.800000,5.500000,5.900000
San Antonio,6.500000,4.900000,5.700000,7.300000,7.500000,6.300000,6.600000,6.500000,NaN,NaN,5.800000,6.700000,5.100000,7.000000,6.500000,5.4,6.800000,6.700000,6.800000,7.300000
San Diego,5.400000,6.600000,6.200000,4.200000,4.500000,5.100000,4.500000,5.000000,NaN,NaN,4.800000,4.900000,3.800000,4.600000,4.200000,3.6,3.400000,4.000000,3.800000,4.500000
San Francisco,3.800000,4.000000,3.800000,4.600000,3.100000,3.600000,3.600000,3.100000,NaN,NaN,3.700000,3.400000,NaN,3.200000,3.600000,2.5,3.600000,NaN,2.500000,3.700000
San Jose,4.700000,4.800000,4.200000,3.600000,4.000000,4.500000,3.800000,3.900000,NaN,NaN,4.100000,3.300000,3.000000,3.100000,4.000000,3.3,3.500000,3.300000,3.300000,4.200000
San Juan,14.100000,9.900000,10.100000,12.800000,11.300000,NaN,NaN,NaN,NaN,NaN,7.700000,9.500000,8.700000,9.800000,9.500000,9.3,9.900000,10.200000,11.100000,NaN
Seattle,6.500000,4.600000,4.800000,4.000000,5.600000,5.200000,4.900000,3.500000,NaN,NaN,3.900000,3.500000,3.700000,5.400000,5.000000,3.7,3.300000,3.600000,3.300000,3.900000
Tucson,5.100000,5.500000,7.400000,6.900000,6.600000,7.300000,8.700000,7.200000,NaN,NaN,5.800000,5.100000,4.200000,4.900000,4.200000,5.5,5.000000,5.100000,4.100000,5.600000
Tulsa,8.200000,9.600000,8.200000,10.100000,8.200000,6.900000,8.900000,8.900000,NaN,NaN,8.400000,7.300000,6.900000,11.200000,8.300000,9.4,7.100000,10.200000,8.700000,7.600000
Virginia Beach,9.400000,6.000000,7.100000,7.200000,6.800000,7.800000,7.800000,10.300000,NaN,NaN,5.500000,6.800000,6.900000,6.100000,5.800000,4.6,5.600000,4.900000,4.600000,5.700000
Wichita,NaN,NaN,NaN,NaN,NaN,8.800000,10.600000,7.700000,NaN,NaN,9.300000,6.900000,7.300000,8.800000,8.900000,6.1,6.600000,8.300000,6.900000,8.100000
Infant Mortality Mean,8.370455,7.895455,7.547727,7.970455,7.547727,7.851163,7.888636,7.781818,13.1,10.8,7.529111,6.695556,6.861364,6.913333,6.884444,6.5,6.722222,6.790909,6.631111,6.411364
Infant Mortality First Quartile,6.425000,5.475000,5.675000,5.875000,5.500000,5.750000,5.475000,5.675000,13.1,10.8,5.300000,4.900000,4.975000,4.900000,4.900000,5.1,5.100000,5.050000,4.600000,4.375000
Infant Mortality Median,7.650000,6.750000,7.200000,7.100000,7.000000,6.900000,7.500000,7.200000,13.1,10.8,7.000000,6.700000,6.800000,6.200000,6.500000,6.1,6.500000,6.650000,6.000000,6.000000
Infant Mortality Third Quartile,9.975000,9.900000,8.975000,9.825000,9.850000,9.350000,9.425000,9.475000,13.1,10.8,8.800000,7.600000,8.225000,8.000000,8.300000,7.9,7.900000,8.500000,7.800000,7.675000

In [92]:
inf_mor.to_csv('../data/cleaned/infant_mortality.csv')

In [121]:
inf_mor = pd.read_csv('../data/cleaned/infant_mortality.csv', index_col='Location')
inf_mor.tail()

,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
Location,,,,,,,,,,,,,,,,,,,,
Wichita,NaN,NaN,NaN,NaN,NaN,8.800000,10.600000,7.700000,NaN,NaN,9.300000,6.900000,7.300000,8.800000,8.900000,6.1,6.600000,8.300000,6.900000,8.100000
Infant Mortality Mean,8.370455,7.895455,7.547727,7.970455,7.547727,7.851163,7.888636,7.781818,13.1,10.8,7.529111,6.695556,6.861364,6.913333,6.884444,6.5,6.722222,6.790909,6.631111,6.411364
Infant Mortality First Quartile,6.425000,5.475000,5.675000,5.875000,5.500000,5.750000,5.475000,5.675000,13.1,10.8,5.300000,4.900000,4.975000,4.900000,4.900000,5.1,5.100000,5.050000,4.600000,4.375000
Infant Mortality Median,7.650000,6.750000,7.200000,7.100000,7.000000,6.900000,7.500000,7.200000,13.1,10.8,7.000000,6.700000,6.800000,6.200000,6.500000,6.1,6.500000,6.650000,6.000000,6.000000
Infant Mortality Third Quartile,9.975000,9.900000,8.975000,9.825000,9.850000,9.350000,9.425000,9.475000,13.1,10.8,8.800000,7.600000,8.225000,8.000000,8.300000,7.9,7.900000,8.500000,7.800000,7.675000

In [124]:
def add_infant_mortality_row(file_location, other_df, row_to_add, new_row_name):
    df = pd.read_csv(file_location, index_col='Unnamed: 0')
    df = df.append(other_df.loc[row_to_add])
    df = df.rename(index={row_to_add: new_row_name})
    return df

In [125]:
add_infant_mortality_row('../data/cleaned/new_york.csv', inf_mor, 'New York City', 'Infant Mortality')

,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
CO 2nd Max 1-hr,10.00,8.500,8.600,6.400,11.200,5.400,4.800,5.400,3.100,3.400,4.200,5.700,4.000,3.200,3.100,3.100,2.700,5.200,2.300,4.800
CO 2nd Max 8-hr,6.60,4.800,4.800,4.400,3.300,3.300,3.400,2.900,2.400,2.100,2.100,2.200,2.800,2.500,1.900,2.500,1.900,2.500,1.600,2.700
NO2 98th Percentile 1-hr,100.00,106.000,100.000,97.000,84.000,81.000,83.000,86.000,79.000,77.000,72.000,71.000,71.000,67.000,62.000,70.000,68.000,60.000,67.000,68.000
NO2 Mean 1-hr,42.00,41.000,40.000,40.000,32.000,30.000,36.000,34.000,34.000,26.000,26.000,22.000,25.000,22.000,22.000,22.000,22.000,20.000,20.000,19.000
Ozone 2nd Max 1-hr,0.15,0.140,0.140,0.150,0.140,0.110,0.140,0.150,0.130,0.130,0.100,0.120,0.120,0.120,0.120,0.110,0.100,0.100,0.110,0.110
Ozone 4th Max 8-hr,0.11,0.114,0.108,0.125,0.102,0.088,0.101,0.101,0.094,0.087,0.081,0.087,0.089,0.085,0.078,0.074,0.079,0.078,0.079,0.079
SO2 99th Percentile 1-hr,79.00,86.000,71.000,67.000,74.000,69.000,72.000,70.000,62.000,62.000,61.000,50.000,41.000,32.000,22.000,15.000,15.000,7.000,7.000,8.000
SO2 2nd Max 24-hr,45.00,46.000,46.000,39.000,51.000,35.000,39.000,34.000,36.000,26.000,26.000,24.000,20.000,12.000,10.000,10.000,7.000,4.000,4.000,4.000
SO2 Mean 1-hr,13.00,13.000,12.000,12.000,11.000,10.000,11.000,10.000,10.000,7.000,6.000,5.000,5.000,3.000,2.000,2.000,2.000,1.000,1.000,1.000
PM2.5 98th Percentile 24-hr,39.00,44.000,42.000,48.000,47.000,45.000,43.000,42.000,39.000,34.000,33.000,28.000,33.000,26.000,31.000,31.000,29.000,21.000,23.000,27.000
PM2.5 Weighted Mean 24-hr,13.70,18.500,18.000,16.700,17.000,15.600,17.000,14.800,16.100,13.500,12.700,11.500,12.200,11.700,10.900,10.500,11.400,10.100,10.300,11.100
PM10 2nd Max 24-hr,73.00,108.000,71.000,60.000,75.000,54.000,66.000,NaN,59.000,74.000,78.000,NaN,63.000,73.000,43.000,47.000,44.000,45.000,32.000,38.000
PM10 Mean 24-hr,35.00,36.000,32.000,25.000,36.000,27.000,30.000,NaN,33.000,29.000,28.000,NaN,30.000,30.000,19.000,17.000,20.000,17.000,16.000,16.000
Lead Max 3-Mo Avg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.080,0.040,1.030,0.060,0.110,0.020,0.030,0.030,0.010,0.000
Infant Mortality,6.70,6.400,5.600,5.900,6.200,6.100,5.600,5.700,NaN,NaN,5.000,4.600,4.500,4.600,4.200,4.000,4.100,3.800,4.200,3.500