In [86]:
import pandas as pd
import numpy as np
from scipy.stats import t
import matplotlib.pyplot as plt
import seaborn as sns
import itertools
plt.style.use('seaborn-darkgrid')

In [7]:
all_air = pd.read_csv('../data/cleaned/air_all_years.csv', index_col='Location')
inf_mor = pd.read_csv('../data/cleaned/infant_mortality_plus_stats.csv', index_col='Location')

In [5]:
all_air

,Year,CO 2nd Max 1-hr,CO 2nd Max 8-hr,NO2 98th Percentile 1-hr,NO2 Mean 1-hr,Ozone 2nd Max 1-hr,Ozone 4th Max 8-hr,SO2 99th Percentile 1-hr,SO2 2nd Max 24-hr,SO2 Mean 1-hr,PM2.5 98th Percentile 24-hr,PM2.5 Weighted Mean 24-hr,PM10 2nd Max 24-hr,PM10 Mean 24-hr,Lead Max 3-Mo Avg
Location,,,,,,,,,,,,,,,
Albuquerque,1999,7.500000,4.600000,54.000000,16.000000,0.100,0.076000,NaN,NaN,NaN,NaN,NaN,93.0,39.00,NaN
Atlanta,1999,6.300000,4.100000,87.000000,24.000000,0.160,0.124000,90.000000,23.000000,5.000,48.000000,23.000000,72.0,35.00,NaN
Austin,1999,2.100000,1.200000,NaN,6.000000,0.110,0.099000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Baltimore,1999,10.200000,5.600000,70.000000,24.000000,0.150,0.113000,79.000000,20.000000,6.000,NaN,NaN,61.0,32.00,NaN
Boston,1999,8.400000,4.200000,77.000000,30.000000,0.120,0.093000,93.000000,40.000000,8.000,47.000000,15.300000,65.0,30.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wichita,2018,NaN,NaN,40.000000,8.000000,0.080,0.067000,4.000000,2.000000,1.000,20.000000,8.200000,86.0,31.00,NaN
National Means,2018,3.068182,1.909091,49.756098,14.214286,0.095,0.075409,14.256410,4.230769,0.725,31.568182,10.120455,100.9,25.15,0.038
National First Quartile,2018,1.700000,1.200000,43.000000,11.000000,0.090,0.071000,3.750000,1.000000,0.000,21.000000,8.900000,41.0,16.00,0.010
National Median,2018,1.900000,1.500000,47.000000,13.000000,0.090,0.073500,8.000000,3.000000,1.000,25.000000,9.850000,63.0,22.50,0.020
National Third Quartile,2018,3.350000,2.250000,58.250000,16.000000,0.100,0.077500,15.564103,4.173077,1.000,29.000000,11.050000,106.5,30.50,0.060

In [17]:
inf_mor

,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
Location,,,,,,,,,,,,,,,,,,,,
Albuquerque,6.900000,6.500000,5.700000,6.900000,4.500000,6.400000,5.100000,5.200000,4.866667,4.533333,4.200000,4.500000,5.500000,6.600000,5.700000,5.9,4.900000,7.200000,5.500000,5.600000
Atlanta,9.200000,7.800000,7.700000,1.300000,1.100000,NaN,3.100000,7.300000,8.500000,9.700000,10.900000,6.700000,9.300000,5.500000,5.500000,7.9,8.400000,6.500000,5.900000,4.600000
Austin,5.100000,4.600000,5.300000,4.600000,6.200000,4.900000,5.400000,5.600000,5.566667,5.533333,5.500000,4.900000,4.400000,4.500000,4.200000,4.6,3.600000,3.400000,3.700000,3.300000
Baltimore,14.100000,11.600000,11.300000,9.900000,12.800000,12.500000,11.200000,12.200000,12.636667,13.073333,13.510000,2.000000,10.800000,10.000000,10.200000,10.4,7.700000,8.500000,8.200000,8.600000
Boston,7.400000,6.700000,7.200000,6.900000,6.100000,6.200000,5.100000,5.900000,6.166667,6.433333,6.700000,3.800000,5.300000,4.900000,4.700000,6.3,5.500000,5.300000,4.700000,4.000000
Charlotte,6.500000,8.900000,8.300000,8.600000,7.200000,9.800000,8.800000,7.300000,6.966667,6.633333,6.300000,6.000000,6.200000,5.600000,6.500000,6.0,6.200000,7.200000,5.100000,4.900000
Chicago,12.200000,10.900000,9.500000,9.000000,10.000000,8.900000,9.100000,7.200000,7.466667,7.733333,8.000000,7.500000,7.900000,7.700000,6.600000,7.0,7.800000,6.900000,6.700000,7.200000
Cleveland,13.000000,13.200000,11.200000,14.700000,10.000000,14.800000,15.000000,14.000000,14.100000,14.200000,14.300000,13.500000,14.100000,13.400000,13.500000,11.3,17.000000,12.200000,13.300000,14.600000
Colorado Springs,8.800000,7.800000,6.200000,6.900000,7.200000,8.700000,7.800000,10.000000,9.066667,8.133333,7.200000,7.600000,7.100000,5.200000,4.800000,4.1,5.500000,5.400000,5.700000,4.300000
Columbus,9.800000,9.900000,9.200000,10.800000,9.800000,8.300000,9.800000,10.000000,9.300000,8.600000,7.900000,7.600000,8.900000,8.000000,7.900000,8.8,9.800000,9.300000,8.800000,8.200000
Dallas,6.800000,5.400000,6.500000,6.800000,8.100000,6.800000,7.300000,8.500000,8.333333,8.166667,8.000000,7.500000,7.500000,7.100000,7.200000,7.2,6.700000,6.000000,7.800000,6.100000
Denver,6.200000,6.000000,5.300000,7.100000,7.000000,6.600000,8.800000,5.200000,5.800000,6.400000,7.000000,6.100000,4.500000,5.600000,7.300000,4.4,5.500000,4.800000,3.500000,4.400000
Detroit,14.600000,14.800000,14.000000,16.700000,16.400000,15.500000,16.000000,13.400000,13.866667,14.333333,14.800000,13.500000,12.400000,15.000000,13.400000,10.5,12.800000,12.900000,14.600000,14.300000
District of Columbia,15.000000,12.000000,10.600000,11.300000,10.500000,12.000000,14.100000,11.300000,10.800000,10.300000,9.800000,7.900000,7.500000,8.000000,6.800000,7.3,8.600000,7.100000,8.100000,6.900000
El Paso,5.000000,4.400000,5.000000,3.500000,3.900000,3.700000,5.100000,4.700000,4.433333,4.166667,3.900000,3.900000,4.900000,4.500000,4.800000,5.1,4.300000,4.200000,4.800000,3.500000
Fresno,6.700000,6.800000,5.900000,8.300000,7.000000,8.000000,7.700000,7.200000,6.833333,6.466667,6.100000,7.400000,8.200000,6.200000,9.200000,8.2,8.000000,5.700000,7.800000,7.200000
Houston,6.500000,5.100000,5.500000,7.100000,6.900000,7.300000,6.900000,5.900000,6.233333,6.566667,6.900000,6.400000,5.500000,6.100000,6.800000,6.1,5.900000,6.000000,6.000000,6.200000
Indianapolis,11.000000,9.900000,7.800000,8.500000,9.400000,10.100000,9.800000,9.300000,9.966667,10.633333,11.300000,9.700000,9.500000,7.400000,9.200000,8.4,7.900000,8.500000,7.300000,7.900000
Jacksonville,10.600000,9.300000,11.300000,9.600000,10.200000,11.300000,12.100000,10.100000,9.666667,9.233333,8.800000,8.200000,8.300000,9.300000,9.600000,9.8,8.400000,9.300000,9.000000,10.500000
Kansas City,8.900000,7.200000,7.600000,9.800000,8.300000,8.200000,7.300000,9.000000,8.366667,7.733333,7.100000,6.200000,5.900000,7.300000,6.000000,6.0,5.600000,6.700000,7.500000,6.400000
Las Vegas,4.900000,3.900000,5.700000,5.300000,3.700000,4.300000,3.500000,5.600000,4.833333,4.066667,3.300000,3.200000,2.400000,3.700000,3.200000,4.2,4.600000,5.100000,4.300000,4.100000
Los Angeles,6.100000,4.900000,5.700000,5.800000,5.500000,5.800000,5.100000,4.800000,4.866667,4.933333,5.000000,5.200000,4.900000,4.600000,4.900000,4.5,4.300000,4.200000,4.400000,4.000000
Louisville,7.400000,7.000000,5.700000,6.900000,4.900000,5.600000,5.500000,7.100000,7.166667,7.233333,7.300000,6.900000,6.700000,7.900000,5.100000,6.6,6.500000,6.100000,6.600000,4.900000
Memphis,13.300000,16.100000,14.900000,16.700000,17.300000,14.700000,13.300000,16.000000,15.633333,15.266667,14.900000,11.700000,10.700000,11.800000,10.500000,10.3,9.900000,10.100000,11.100000,10.000000
Miami,5.200000,5.400000,4.900000,4.700000,5.100000,4.300000,7.900000,3.800000,4.300000,4.800000,5.300000,4.700000,5.000000,4.800000,5.200000,5.5,5.800000,6.600000,5.200000,4.500000
Milwaukee,10.500000,11.400000,11.500000,12.100000,11.400000,11.900000,11.100000,11.900000,11.633333,11.366667,11.100000,9.400000,9.300000,9.600000,11.300000,8.5,9.500000,9.400000,12.300000,10.800000
Minneapolis,7.900000,6.200000,5.600000,6.700000,5.500000,6.900000,5.800000,6.900000,6.166667,5.433333,4.700000,6.800000,6.500000,5.300000,7.400000,7.2,7.200000,7.000000,5.800000,6.500000
Nashville,9.200000,10.200000,8.700000,10.200000,7.400000,6.300000,8.100000,9.300000,8.800000,8.300000,7.800000,7.800000,7.600000,7.000000,7.600000,6.5,7.100000,7.300000,7.000000,6.700000
New York City,6.700000,6.400000,5.600000,5.900000,6.200000,6.100000,5.600000,5.700000,5.466667,5.233333,5.000000,4.600000,4.500000,4.600000,4.200000,4.0,4.100000,3.800000,4.200000,3.500000
Oklahoma City,9.300000,12.600000,8.900000,8.700000,10.300000,10.600000,9.300000,7.000000,8.333333,9.666667,11.000000,8.100000,7.200000,8.200000,7.900000,7.0,7.400000,8.900000,7.400000,8.100000
Omaha,7.900000,8.900000,7.500000,9.800000,7.300000,6.200000,6.500000,7.900000,7.266667,6.633333,6.000000,6.500000,6.200000,4.400000,7.800000,5.2,7.000000,7.400000,7.200000,6.700000
Philadelphia,12.200000,10.500000,10.500000,10.700000,10.700000,11.200000,12.000000,12.200000,11.833333,11.466667,11.100000,10.500000,9.500000,10.000000,9.300000,7.3,8.000000,8.500000,8.300000,8.100000
Phoenix,8.000000,6.700000,7.900000,6.600000,6.800000,7.200000,6.700000,6.800000,6.833333,6.866667,6.900000,7.000000,7.500000,6.400000,5.600000,6.7,5.400000,6.500000,5.900000,5.700000
Portland,5.200000,5.900000,3.200000,4.500000,3.900000,5.300000,5.900000,5.800000,5.600000,5.400000,5.200000,5.400000,4.300000,4.800000,4.400000,5.1,5.100000,3.700000,4.100000,3.300000
Sacramento,6.500000,6.600000,7.200000,7.100000,5.900000,5.700000,5.900000,6.200000,6.466667,6.733333,7.000000,5.200000,6.300000,6.000000,5.500000,5.2,5.700000,4.800000,5.500000,5.900000
San Antonio,6.500000,4.900000,5.700000,7.300000,7.500000,6.300000,6.600000,6.500000,6.266667,6.033333,5.800000,6.700000,5.100000,7.000000,6.500000,5.4,6.800000,6.700000,6.800000,7.300000
San Diego,5.400000,6.600000,6.200000,4.200000,4.500000,5.100000,4.500000,5.000000,4.933333,4.866667,4.800000,4.900000,3.800000,4.600000,4.200000,3.6,3.400000,4.000000,3.800000,4.500000
San Francisco,3.800000,4.000000,3.800000,4.600000,3.100000,3.600000,3.600000,3.100000,3.300000,3.500000,3.700000,3.400000,NaN,3.200000,3.600000,2.5,3.600000,NaN,2.500000,3.700000
San Jose,4.700000,4.800000,4.200000,3.600000,4.000000,4.500000,3.800000,3.900000,3.966667,4.033333,4.100000,3.300000,3.000000,3.100000,4.000000,3.3,3.500000,3.300000,3.300000,4.200000
San Juan,14.100000,9.900000,10.100000,12.800000,11.300000,NaN,NaN,NaN,NaN,NaN,7.700000,9.500000,8.700000,9.800000,9.500000,9.3,9.900000,10.200000,11.100000,NaN
Seattle,6.500000,4.600000,4.800000,4.000000,5.600000,5.200000,4.900000,3.500000,3.633333,3.766667,3.900000,3.500000,3.700000,5.400000,5.000000,3.7,3.300000,3.600000,3.300000,3.900000
Tucson,5.100000,5.500000,7.400000,6.900000,6.600000,7.300000,8.700000,7.200000,6.733333,6.266667,5.800000,5.100000,4.200000,4.900000,4.200000,5.5,5.000000,5.100000,4.100000,5.600000
Tulsa,8.200000,9.600000,8.200000,10.100000,8.200000,6.900000,8.900000,8.900000,8.733333,8.566667,8.400000,7.300000,6.900000,11.200000,8.300000,9.4,7.100000,10.200000,8.700000,7.600000
Virginia Beach,9.400000,6.000000,7.100000,7.200000,6.800000,7.800000,7.800000,10.300000,8.700000,7.100000,5.500000,6.800000,6.900000,6.100000,5.800000,4.6,5.600000,4.900000,4.600000,5.700000
Wichita,NaN,NaN,NaN,NaN,NaN,8.800000,10.600000,7.700000,8.233333,8.766667,9.300000,6.900000,7.300000,8.800000,8.900000,6.1,6.600000,8.300000,6.900000,8.100000
Infant Mortality Mean,8.370455,7.895455,7.547727,7.970455,7.547727,7.851163,7.888636,7.781818,7.696288,7.610758,7.529111,6.695556,6.861364,6.913333,6.884444,6.5,6.722222,6.790909,6.631111,6.411364
Infant Mortality First Quartile,6.425000,5.475000,5.675000,5.875000,5.500000,5.750000,5.475000,5.675000,5.591667,5.425000,5.300000,4.900000,4.975000,4.900000,4.900000,5.1,5.100000,5.050000,4.600000,4.375000
Infant Mortality Median,7.650000,6.750000,7.200000,7.100000,7.000000,6.900000,7.500000,7.200000,7.066667,6.800000,7.000000,6.700000,6.800000,6.200000,6.500000,6.1,6.500000,6.650000,6.000000,6.000000
Infant Mortality Third Quartile,9.975000,9.900000,8.975000,9.825000,9.850000,9.350000,9.425000,9.475000,8.866667,8.883333,8.800000,7.600000,8.225000,8.000000,8.300000,7.9,7.900000,8.500000,7.800000,7.675000

In [14]:
all_air.index

Index(['Albuquerque', 'Atlanta', 'Austin', 'Baltimore', 'Boston', 'Charlotte',
       'Chicago', 'Cleveland', 'Colorado Springs', 'Columbus',
       ...
       'Seattle', 'Tucson', 'Tulsa', 'Virginia Beach', 'District of Columbia',
       'Wichita', 'National Means', 'National First Quartile',
       'National Median', 'National Third Quartile'],
      dtype='object', name='Location', length=980)

In [40]:
inf_mor.columns = inf_mor.columns.astype(int)
inf_mor.columns.dtype

dtype('int64')

In [37]:
all_air.info()

<class 'pandas.core.frame.DataFrame'>
Index: 980 entries, Albuquerque to National Third Quartile
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Year                         980 non-null    int64
 1   CO 2nd Max 1-hr              959 non-null    float64
 2   CO 2nd Max 8-hr              963 non-null    float64
 3   NO2 98th Percentile 1-hr     831 non-null    float64
 4   NO2 Mean 1-hr                873 non-null    float64
 5   Ozone 2nd Max 1-hr           974 non-null    float64
 6   Ozone 4th Max 8-hr           974 non-null    float64
 7   SO2 99th Percentile 1-hr     835 non-null    float64
 8   SO2 2nd Max 24-hr            836 non-null    float64
 9   SO2 Mean 1-hr                838 non-null    float64
 10  PM2.5 98th Percentile 24-hr  920 non-null    float64
 11  PM2.5 Weighted Mean 24-hr    920 non-null    float64
 12  PM10 2nd Max 24-hr           945 non-null    float64
 13  PM10 Mean 24-hr              945 non-null    float64
 14  Lead Max 3-Mo Avg            257 non-null    float64
dtypes: float64(14), int64(1)
memory usage: 138.7+ KB

In [89]:
def get_pvalue_from_corr(r, n):
    t_stat = (r*(np.sqrt(n-2)))/(np.sqrt(1-r**2))
    return t.sf(abs(t_stat), df=n-2)

In [120]:
def correlation_by_city(air_df, inf_mor_df):
    inf_mor.columns = inf_mor.columns.astype(int)
    city_dfs = []
    n=20
    for city in air_df.index:
        if city not in ['National Means', 'National First Quartile', 'National Median', 'National Third Quartile']:
            df = air_df.loc[city]
#             df.set_index('Year', drop=True, inplace=True)
#             df = df.transpose()
#             df = df.append(inf_mor_df.loc[city])
#             df = df.rename(index={city:'Infant Mortality'})
#             df.drop(index='Lead Max 3-Mo Avg', inplace=True)
#             corr = df.corrwith(df.loc['Infant Mortality'], axis=1)
#             corr = pd.DataFrame(data=corr, columns=['Correlation Coefficient'])
#             corr.drop(index='Infant Mortality', inplace=True)
#             corr.reset_index(inplace=True)
#             corr.insert(0, 'Location', city)
#             corr['p-value'] = get_pvalue_from_corr(corr['Correlation Coefficient'], n)
#             corr['Significant?'] = corr['p-value'] <= .025
#             city_dfs.append(corr)
#     return city_dfs
    return df

In [121]:
correlation_by_city(all_air, inf_mor)

IndexError: list index out of range