In [162]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt

In [163]:
inf_mor_1999 = pd.read_csv('../data/infant_mortality_1999_2008.txt')
inf_mor_2009 = pd.read_csv('../data/infant_mortality_2009_2018.txt')

In [164]:
inf_mor_1999.head()

,Location,Data Type,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008
0,Albuquerque,Rate per 1000,6.9,6.5,5.7,6.9,4.5,6.4,5.1,5.2,NaN,NaN
1,Atlanta,Rate per 1000,9.2,7.8,7.7,1.3,1.1,N.A.,3.1,7.3,NaN,NaN
2,Austin,Rate per 1000,5.1,4.6,5.3,4.6,6.2,4.9,5.4,5.6,NaN,NaN
3,Baltimore,Rate per 1000,14.1,11.6,11.3,9.9,12.8,12.5,11.2,12.2,NaN,NaN
4,Boston,Rate per 1000,7.4,6.7,7.2,6.9,6.1,6.2,5.1,5.9,NaN,NaN

In [165]:
inf_mor_2009.head()

,Location,Data Type,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Albuquerque,Rate per 1000,4.20,4.5,5.5,6.6,5.7,5.9,4.9,7.2,5.5,5.6
1,Arlington,Rate per 1000,NaN,8.2,5.2,6.5,5.1,6.1,7.6,5.0,4.3,6.7
2,Atlanta,Rate per 1000,10.90,6.7,9.3,5.5,5.5,7.9,8.4,6.5,5.9,4.6
3,Austin,Rate per 1000,5.50,4.9,4.4,4.5,4.2,4.6,3.6,3.4,3.7,3.3
4,Baltimore,Rate per 1000,13.51,2.0,10.8,10.0,10.2,10.4,7.7,8.5,8.2,8.6

In [166]:
cities_1999 = inf_mor_1999['Location'].unique()

In [167]:
# only interested in cities that appear in both datasets
inf_mor_2009 = inf_mor_2009.loc[inf_mor_2009['Location'].isin(cities_1999)]
inf_mor_2009.head()

,Location,Data Type,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Albuquerque,Rate per 1000,4.20,4.5,5.5,6.6,5.7,5.9,4.9,7.2,5.5,5.6
2,Atlanta,Rate per 1000,10.90,6.7,9.3,5.5,5.5,7.9,8.4,6.5,5.9,4.6
3,Austin,Rate per 1000,5.50,4.9,4.4,4.5,4.2,4.6,3.6,3.4,3.7,3.3
4,Baltimore,Rate per 1000,13.51,2.0,10.8,10.0,10.2,10.4,7.7,8.5,8.2,8.6
5,Boston,Rate per 1000,6.70,3.8,5.3,4.9,4.7,6.3,5.5,5.3,4.7,4.0

In [168]:
inf_mor_2009.reset_index(drop=True, inplace=True)

In [169]:
inf_mor_2009.head()

,Location,Data Type,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Albuquerque,Rate per 1000,4.20,4.5,5.5,6.6,5.7,5.9,4.9,7.2,5.5,5.6
1,Atlanta,Rate per 1000,10.90,6.7,9.3,5.5,5.5,7.9,8.4,6.5,5.9,4.6
2,Austin,Rate per 1000,5.50,4.9,4.4,4.5,4.2,4.6,3.6,3.4,3.7,3.3
3,Baltimore,Rate per 1000,13.51,2.0,10.8,10.0,10.2,10.4,7.7,8.5,8.2,8.6
4,Boston,Rate per 1000,6.70,3.8,5.3,4.9,4.7,6.3,5.5,5.3,4.7,4.0

In [170]:
# merge two datasets into one to show 20 years
inf_mor = inf_mor_1999.merge(inf_mor_2009, how='inner', on='Location')

In [171]:
inf_mor

,Location,Data Type_x,1999,2000,2001,2002,2003,2004,2005,2006,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Albuquerque,Rate per 1000,6.9,6.5,5.7,6.9,4.5,6.4,5.1,5.2,...,4.20,4.5,5.5,6.6,5.7,5.9,4.9,7.2,5.5,5.6
1,Atlanta,Rate per 1000,9.2,7.8,7.7,1.3,1.1,N.A.,3.1,7.3,...,10.90,6.7,9.3,5.5,5.5,7.9,8.4,6.5,5.9,4.6
2,Austin,Rate per 1000,5.1,4.6,5.3,4.6,6.2,4.9,5.4,5.6,...,5.50,4.9,4.4,4.5,4.2,4.6,3.6,3.4,3.7,3.3
3,Baltimore,Rate per 1000,14.1,11.6,11.3,9.9,12.8,12.5,11.2,12.2,...,13.51,2.0,10.8,10.0,10.2,10.4,7.7,8.5,8.2,8.6
4,Boston,Rate per 1000,7.4,6.7,7.2,6.9,6.1,6.2,5.1,5.9,...,6.70,3.8,5.3,4.9,4.7,6.3,5.5,5.3,4.7,4.0
5,Charlotte,Rate per 1000,6.5,8.9,8.3,8.6,7.2,9.8,8.8,7.3,...,6.30,6.0,6.2,5.6,6.5,6.0,6.2,7.2,5.1,4.9
6,Chicago,Rate per 1000,12.2,10.9,9.5,9.0,10.0,8.9,9.1,7.2,...,8.00,7.5,7.9,7.7,6.6,7.0,7.8,6.9,6.7,7.2
7,Cleveland,Rate per 1000,13.0,13.2,11.2,14.7,10.0,14.8,15.0,14.0,...,14.30,13.5,14.1,13.4,13.5,11.3,17.0,12.2,13.3,14.6
8,Colorado Springs,Rate per 1000,8.8,7.8,6.2,6.9,7.2,8.7,7.8,10.0,...,7.20,7.6,7.1,5.2,4.8,4.1,5.5,5.4,5.7,4.3
9,Columbus,Rate per 1000,9.8,9.9,9.2,10.8,9.8,8.3,9.8,10.0,...,7.90,7.6,8.9,8.0,7.9,8.8,9.8,9.3,8.8,8.2
10,Dallas,Rate per 1000,6.8,5.4,6.5,6.8,8.1,6.8,7.3,8.5,...,8.00,7.5,7.5,7.1,7.2,7.2,6.7,6.0,7.8,6.1
11,Denver,Rate per 1000,6.2,6.0,5.3,7.1,7.0,6.6,8.8,5.2,...,7.00,6.1,4.5,5.6,7.3,4.4,5.5,4.8,3.5,4.4
12,Detroit,Rate per 1000,14.6,14.8,14.0,16.7,16.4,15.5,16.0,13.4,...,14.80,13.5,12.4,15.0,13.4,10.5,12.8,12.9,14.6,14.3
13,District of Columbia,Rate per 1000,15.0,12.0,10.6,11.3,10.5,12.0,14.1,11.3,...,9.80,7.9,7.5,8.0,6.8,7.3,8.6,7.1,8.1,6.9
14,El Paso,Rate per 1000,5.0,4.4,5.0,3.5,3.9,3.7,5.1,4.7,...,3.90,3.9,4.9,4.5,4.8,5.1,4.3,4.2,4.8,3.5
15,Fort Worth,Rate per 1000,9.2,6.3,8.7,7.5,8.8,6.8,8.1,7.8,...,8.20,9.0,8.4,7.7,8.6,8.4,6.5,6.9,6.9,6.9
16,Fresno,Rate per 1000,6.7,6.8,5.9,8.3,7.0,8.0,7.7,7.2,...,6.10,7.4,8.2,6.2,9.2,8.2,8.0,5.7,7.8,7.2
17,Houston,Rate per 1000,6.5,5.1,5.5,7.1,6.9,7.3,6.9,5.9,...,6.90,6.4,5.5,6.1,6.8,6.1,5.9,6.0,6.0,6.2
18,Indianapolis,Rate per 1000,11.0,9.9,7.8,8.5,9.4,10.1,9.8,9.3,...,11.30,9.7,9.5,7.4,9.2,8.4,7.9,8.5,7.3,7.9
19,Jacksonville,Rate per 1000,10.6,9.3,11.3,9.6,10.2,11.3,12.1,10.1,...,8.80,8.2,8.3,9.3,9.6,9.8,8.4,9.3,9.0,10.5
20,Kansas City,Rate per 1000,8.9,7.2,7.6,9.8,8.3,8.2,7.3,9.0,...,7.10,6.2,5.9,7.3,6.0,6.0,5.6,6.7,7.5,6.4
21,Las Vegas,Rate per 1000,4.9,3.9,5.7,5.3,3.7,4.3,3.5,5.6,...,3.30,3.2,2.4,3.7,3.2,4.2,4.6,5.1,4.3,4.1
22,Long Beach,Rate per 1000,6.1,6.6,4.6,4.3,7.0,4.3,4.4,4.6,...,6.20,4.2,4.8,4.3,3.2,3.7,5.3,3.9,S,S
23,Los Angeles,Rate per 1000,6.1,4.9,5.7,5.8,5.5,5.8,5.1,4.8,...,5.00,5.2,4.9,4.6,4.9,4.5,4.3,4.2,4.4,4.0
24,Louisville,Rate per 1000,7.4,7.0,5.7,6.9,4.9,5.6,5.5,7.1,...,7.30,6.9,6.7,7.9,5.1,6.6,6.5,6.1,6.6,4.9
25,Memphis,Rate per 1000,13.3,16.1,14.9,16.7,17.3,14.7,13.3,16.0,...,14.90,11.7,10.7,11.8,10.5,10.3,9.9,10.1,11.1,10.0
26,Mesa,Rate per 1000,7.6,7.2,5.2,5.2,6.1,6.6,6.0,5.7,...,5.50,5.2,5.3,4.8,6.7,6.4,5.8,5.3,6.8,6.0
27,Miami,Rate per 1000,5.2,5.4,4.9,4.7,5.1,4.3,7.9,3.8,...,5.30,4.7,5.0,4.8,5.2,5.5,5.8,6.6,5.2,4.5
28,Milwaukee,Rate per 1000,10.5,11.4,11.5,12.1,11.4,11.9,11.1,11.9,...,11.10,9.4,9.3,9.6,11.3,8.5,9.5,9.4,12.3,10.8
29,Minneapolis,Rate per 1000,7.9,6.2,5.6,6.7,5.5,6.9,5.8,6.9,...,4.70,6.8,6.5,5.3,7.4,7.2,7.2,7.0,5.8,6.5
30,Nashville-Davidson,Rate per 1000,9.2,10.2,8.7,10.2,7.4,6.3,8.1,9.3,...,7.80,7.8,7.6,7.0,7.6,6.5,7.1,7.3,7.0,6.7
31,New York City,Rate per 1000,6.7,6.4,5.6,5.9,6.2,6.1,5.6,5.7,...,5.00,4.6,4.5,4.6,4.2,4.0,4.1,3.8,4.2,3.5
32,Oakland,Rate per 1000,6.5,5.9,7.8,5.4,6.5,6.2,6.8,5.1,...,5.70,6.5,5.0,6.4,5.7,6.1,5.2,4.5,3.7,4.7
33,Oklahoma City,Rate per 1000,9.3,12.6,8.9,8.7,10.3,10.6,9.3,7.0,...,11.00,8.1,7.2,8.2,7.9,7.0,7.4,8.9,7.4,8.1
34,Omaha,Rate per 1000,7.9,8.9,7.5,9.8,7.3,6.2,6.5,7.9,...,6.00,6.5,6.2,4.4,7.8,5.2,7.0,7.4,7.2,6.7
35,Philadelphia,Rate per 1000,12.2,10.5,10.5,10.7,10.7,11.2,12.0,12.2,...,11.10,10.5,9.5,10.0,9.3,7.3,8.0,8.5,8.3,8.1
36,Phoenix,Rate per 1000,8.0,6.7,7.9,6.6,6.8,7.2,6.7,6.8,...,6.90,7.0,7.5,6.4,5.6,6.7,5.4,6.5,5.9,5.7
37,Portland,Rate per 1000,5.2,5.9,3.2,4.5,3.9,5.3,5.9,5.8,...,5.20,5.4,4.3,4.8,4.4,5.1,5.1,3.7,4.1,3.3
38,Sacramento,Rate per 1000,6.5,6.6,7.2,7.1,5.9,5.7,5.9,6.2,...,7.00,5.2,6.3,6.0,5.5,5.2,5.7,4.8,5.5,5.9
39,San Antonio,Rate per 1000,6.5,4.9,5.7,7.3,7.5,6.3,6.6,6.5,...,5.80,6.7,5.1,7.0,6.5,5.4,6.8,6.7,6.8,7.3
40,San Diego,Rate per 1000,5.4,6.6,6.2,4.2,4.5,5.1,4.5,5.0,...,4.80,4.9,3.8,4.6,4.2,3.6,3.4,4.0,3.8,4.5
41,San Francisco,Rate per 1000,3.8,4.0,3.8,4.6,3.1,3.6,3.6,3.1,...,3.70,3.4,S,3.2,3.6,2.5,3.6,S,2.5,3.7
42,San Jose,Rate per 1000,4.7,4.8,4.2,3.6,4.0,4.5,3.8,3.9,...,4.10,3.3,3.0,3.1,4.0,3.3,3.5,3.3,3.3,4.2
43,San Juan,Rate per 1000,14.1,9.9,10.1,12.8,11.3,N.A.,N.A.,N.A.,...,7.70,9.5,8.7,9.8,9.5,9.3,9.9,10.2,11.1,S
44,Seattle,Rate per 1000,6.5,4.6,4.8,4.0,5.6,5.2,4.9,3.5,...,3.90,3.5,3.7,5.4,5.0,3.7,3.3,3.6,3.3,3.9
45,Tucson,Rate per 1000,5.1,5.5,7.4,6.9,6.6,7.3,8.7,7.2,...,5.80,5.1,4.2,4.9,4.2,5.5,5.0,5.1,4.1,5.6
46,Tulsa,Rate per 1000,8.2,9.6,8.2,10.1,8.2,6.9,8.9,8.9,...,8.40,7.3,6.9,11.2,8.3,9.4,7.1,10.2,8.7,7.6
47,Virginia Beach,Rate per 1000,9.4,6.0,7.1,7.2,6.8,7.8,7.8,10.3,...,5.50,6.8,6.9,6.1,5.8,4.6,5.6,4.9,4.6,5.7
48,Wichita,Rate per 1000,N.A.,N.A.,N.A.,N.A.,N.A.,8.8,10.6,7.7,...,9.30,6.9,7.3,8.8,8.9,6.1,6.6,8.3,6.9,8.1

In [172]:
inf_mor.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 49 entries, 0 to 48
Data columns (total 23 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Location     49 non-null     object
 1   Data Type_x  49 non-null     object
 2   1999         49 non-null     object
 3   2000         49 non-null     object
 4   2001         49 non-null     object
 5   2002         49 non-null     object
 6   2003         49 non-null     object
 7   2004         49 non-null     object
 8   2005         49 non-null     object
 9   2006         49 non-null     object
 10  2007         1 non-null      float64
 11  2008         1 non-null      float64
 12  Data Type_y  49 non-null     object
 13  2009         49 non-null     float64
 14  2010         49 non-null     float64
 15  2011         49 non-null     object
 16  2012         49 non-null     float64
 17  2013         49 non-null     float64
 18  2014         49 non-null     float64
 19  2015         49 non-null     float64
 20  2016         49 non-null     object
 21  2017         49 non-null     object
 22  2018         49 non-null     object
dtypes: float64(8), object(15)
memory usage: 9.2+ KB

In [173]:
# column Data_Type_y is redundant; drop it
inf_mor.drop('Data Type_y', axis=1, inplace=True)

In [174]:
# confirm drop
inf_mor.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 49 entries, 0 to 48
Data columns (total 22 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Location     49 non-null     object
 1   Data Type_x  49 non-null     object
 2   1999         49 non-null     object
 3   2000         49 non-null     object
 4   2001         49 non-null     object
 5   2002         49 non-null     object
 6   2003         49 non-null     object
 7   2004         49 non-null     object
 8   2005         49 non-null     object
 9   2006         49 non-null     object
 10  2007         1 non-null      float64
 11  2008         1 non-null      float64
 12  2009         49 non-null     float64
 13  2010         49 non-null     float64
 14  2011         49 non-null     object
 15  2012         49 non-null     float64
 16  2013         49 non-null     float64
 17  2014         49 non-null     float64
 18  2015         49 non-null     float64
 19  2016         49 non-null     object
 20  2017         49 non-null     object
 21  2018         49 non-null     object
dtypes: float64(8), object(14)
memory usage: 8.8+ KB

In [ ]:
# Rename Data Type_x to Data Type
inf_mor.columns.rename({'Data Type_x': 'data_type'}, inplace=True)

In [176]:
# need to replace values causing numeric columns to appear as dtype=object; first check unique values
inf_mor['1999'].unique()

array(['6.9', '9.2', '5.1', '14.1', '7.4', '6.5', '12.2', '13.0', '8.8',
       '9.8', '6.8', '6.2', '14.6', '15.0', '5.0', '6.7', '11.0', '10.6',
       '8.9', '4.9', '6.1', '13.3', '7.6', '5.2', '10.5', '7.9', '9.3',
       '8.0', '5.4', '3.8', '4.7', '8.2', '9.4', 'N.A.'], dtype=object)

In [177]:
# notice that 'N.A.' appears; replace all instances with np.nan
inf_mor.replace('N.A.', np.nan, inplace=True)
inf_mor.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 49 entries, 0 to 48
Data columns (total 22 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Location     49 non-null     object
 1   Data Type_x  49 non-null     object
 2   1999         48 non-null     object
 3   2000         48 non-null     object
 4   2001         48 non-null     object
 5   2002         48 non-null     object
 6   2003         48 non-null     object
 7   2004         47 non-null     object
 8   2005         48 non-null     object
 9   2006         48 non-null     object
 10  2007         1 non-null      float64
 11  2008         1 non-null      float64
 12  2009         49 non-null     float64
 13  2010         49 non-null     float64
 14  2011         49 non-null     object
 15  2012         49 non-null     float64
 16  2013         49 non-null     float64
 17  2014         49 non-null     float64
 18  2015         49 non-null     float64
 19  2016         49 non-null     object
 20  2017         49 non-null     object
 21  2018         49 non-null     object
dtypes: float64(8), object(14)
memory usage: 8.8+ KB

In [178]:
# try to cast columns to floats
years = inf_mor.columns[2:]
for year in years:
    inf_mor[year] = pd.to_numeric(inf_mor[year])
inf_mor.info()

ValueError: Unable to parse string "S" at position 41

In [179]:
# replace 'S' win np.nan
inf_mor.replace('S', np.nan, inplace=True)

In [180]:
inf_mor.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 49 entries, 0 to 48
Data columns (total 22 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Location     49 non-null     object
 1   Data Type_x  49 non-null     object
 2   1999         48 non-null     float64
 3   2000         48 non-null     float64
 4   2001         48 non-null     float64
 5   2002         48 non-null     float64
 6   2003         48 non-null     float64
 7   2004         47 non-null     float64
 8   2005         48 non-null     float64
 9   2006         48 non-null     float64
 10  2007         1 non-null      float64
 11  2008         1 non-null      float64
 12  2009         49 non-null     float64
 13  2010         49 non-null     float64
 14  2011         48 non-null     object
 15  2012         49 non-null     float64
 16  2013         49 non-null     float64
 17  2014         49 non-null     float64
 18  2015         49 non-null     float64
 19  2016         48 non-null     object
 20  2017         48 non-null     object
 21  2018         47 non-null     object
dtypes: float64(16), object(6)
memory usage: 8.8+ KB

In [181]:
# try again
for year in years:
    inf_mor[year] = pd.to_numeric(inf_mor[year])
inf_mor.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 49 entries, 0 to 48
Data columns (total 22 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Location     49 non-null     object
 1   Data Type_x  49 non-null     object
 2   1999         48 non-null     float64
 3   2000         48 non-null     float64
 4   2001         48 non-null     float64
 5   2002         48 non-null     float64
 6   2003         48 non-null     float64
 7   2004         47 non-null     float64
 8   2005         48 non-null     float64
 9   2006         48 non-null     float64
 10  2007         1 non-null      float64
 11  2008         1 non-null      float64
 12  2009         49 non-null     float64
 13  2010         49 non-null     float64
 14  2011         48 non-null     float64
 15  2012         49 non-null     float64
 16  2013         49 non-null     float64
 17  2014         49 non-null     float64
 18  2015         49 non-null     float64
 19  2016         48 non-null     float64
 20  2017         48 non-null     float64
 21  2018         47 non-null     float64
dtypes: float64(20), object(2)
memory usage: 8.8+ KB

In [182]:
inf_mor.describe()

,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
count,48.000000,48.000000,48.000000,48.000000,48.000000,47.000000,48.000000,48.000000,1.0,1.0,49.000000,49.000000,48.000000,49.000000,49.000000,49.000000,49.000000,48.000000,48.000000,47.000000
mean,8.285417,7.779167,7.466667,7.772917,7.510417,7.691489,7.758333,7.616667,13.1,10.8,7.436939,6.657143,6.779167,6.822449,6.816327,6.471429,6.638776,6.654167,6.579167,6.376596
std,2.929817,2.923781,2.591339,3.277047,3.131803,2.966247,3.069260,2.916814,NaN,NaN,2.941850,2.473105,2.412993,2.571581,2.467231,2.116995,2.492306,2.305494,2.656582,2.563389
min,3.800000,3.900000,3.200000,1.300000,1.100000,3.600000,3.100000,3.100000,13.1,10.8,3.300000,2.000000,2.400000,3.100000,3.200000,2.500000,3.300000,3.300000,2.500000,3.300000
25%,6.425000,5.800000,5.600000,5.375000,5.575000,5.750000,5.475000,5.600000,13.1,10.8,5.500000,4.900000,4.975000,4.800000,4.900000,5.100000,5.200000,4.875000,4.550000,4.450000
50%,7.500000,6.700000,7.200000,7.100000,7.000000,6.800000,7.300000,7.150000,13.1,10.8,6.900000,6.700000,6.600000,6.200000,6.500000,6.100000,6.200000,6.550000,6.300000,6.000000
75%,9.500000,9.900000,8.750000,9.800000,9.500000,8.850000,9.150000,9.300000,13.1,10.8,8.400000,7.600000,8.225000,8.000000,8.300000,7.900000,7.800000,8.350000,7.800000,7.450000
max,15.000000,16.100000,14.900000,16.700000,17.300000,15.500000,16.000000,16.000000,13.1,10.8,14.900000,13.500000,14.100000,15.000000,13.500000,11.300000,17.000000,12.900000,14.600000,14.600000

In [183]:
inf_mor

,Location,Data Type_x,1999,2000,2001,2002,2003,2004,2005,2006,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Albuquerque,Rate per 1000,6.9,6.5,5.7,6.9,4.5,6.4,5.1,5.2,...,4.20,4.5,5.5,6.6,5.7,5.9,4.9,7.2,5.5,5.6
1,Atlanta,Rate per 1000,9.2,7.8,7.7,1.3,1.1,NaN,3.1,7.3,...,10.90,6.7,9.3,5.5,5.5,7.9,8.4,6.5,5.9,4.6
2,Austin,Rate per 1000,5.1,4.6,5.3,4.6,6.2,4.9,5.4,5.6,...,5.50,4.9,4.4,4.5,4.2,4.6,3.6,3.4,3.7,3.3
3,Baltimore,Rate per 1000,14.1,11.6,11.3,9.9,12.8,12.5,11.2,12.2,...,13.51,2.0,10.8,10.0,10.2,10.4,7.7,8.5,8.2,8.6
4,Boston,Rate per 1000,7.4,6.7,7.2,6.9,6.1,6.2,5.1,5.9,...,6.70,3.8,5.3,4.9,4.7,6.3,5.5,5.3,4.7,4.0
5,Charlotte,Rate per 1000,6.5,8.9,8.3,8.6,7.2,9.8,8.8,7.3,...,6.30,6.0,6.2,5.6,6.5,6.0,6.2,7.2,5.1,4.9
6,Chicago,Rate per 1000,12.2,10.9,9.5,9.0,10.0,8.9,9.1,7.2,...,8.00,7.5,7.9,7.7,6.6,7.0,7.8,6.9,6.7,7.2
7,Cleveland,Rate per 1000,13.0,13.2,11.2,14.7,10.0,14.8,15.0,14.0,...,14.30,13.5,14.1,13.4,13.5,11.3,17.0,12.2,13.3,14.6
8,Colorado Springs,Rate per 1000,8.8,7.8,6.2,6.9,7.2,8.7,7.8,10.0,...,7.20,7.6,7.1,5.2,4.8,4.1,5.5,5.4,5.7,4.3
9,Columbus,Rate per 1000,9.8,9.9,9.2,10.8,9.8,8.3,9.8,10.0,...,7.90,7.6,8.9,8.0,7.9,8.8,9.8,9.3,8.8,8.2
10,Dallas,Rate per 1000,6.8,5.4,6.5,6.8,8.1,6.8,7.3,8.5,...,8.00,7.5,7.5,7.1,7.2,7.2,6.7,6.0,7.8,6.1
11,Denver,Rate per 1000,6.2,6.0,5.3,7.1,7.0,6.6,8.8,5.2,...,7.00,6.1,4.5,5.6,7.3,4.4,5.5,4.8,3.5,4.4
12,Detroit,Rate per 1000,14.6,14.8,14.0,16.7,16.4,15.5,16.0,13.4,...,14.80,13.5,12.4,15.0,13.4,10.5,12.8,12.9,14.6,14.3
13,District of Columbia,Rate per 1000,15.0,12.0,10.6,11.3,10.5,12.0,14.1,11.3,...,9.80,7.9,7.5,8.0,6.8,7.3,8.6,7.1,8.1,6.9
14,El Paso,Rate per 1000,5.0,4.4,5.0,3.5,3.9,3.7,5.1,4.7,...,3.90,3.9,4.9,4.5,4.8,5.1,4.3,4.2,4.8,3.5
15,Fort Worth,Rate per 1000,9.2,6.3,8.7,7.5,8.8,6.8,8.1,7.8,...,8.20,9.0,8.4,7.7,8.6,8.4,6.5,6.9,6.9,6.9
16,Fresno,Rate per 1000,6.7,6.8,5.9,8.3,7.0,8.0,7.7,7.2,...,6.10,7.4,8.2,6.2,9.2,8.2,8.0,5.7,7.8,7.2
17,Houston,Rate per 1000,6.5,5.1,5.5,7.1,6.9,7.3,6.9,5.9,...,6.90,6.4,5.5,6.1,6.8,6.1,5.9,6.0,6.0,6.2
18,Indianapolis,Rate per 1000,11.0,9.9,7.8,8.5,9.4,10.1,9.8,9.3,...,11.30,9.7,9.5,7.4,9.2,8.4,7.9,8.5,7.3,7.9
19,Jacksonville,Rate per 1000,10.6,9.3,11.3,9.6,10.2,11.3,12.1,10.1,...,8.80,8.2,8.3,9.3,9.6,9.8,8.4,9.3,9.0,10.5
20,Kansas City,Rate per 1000,8.9,7.2,7.6,9.8,8.3,8.2,7.3,9.0,...,7.10,6.2,5.9,7.3,6.0,6.0,5.6,6.7,7.5,6.4
21,Las Vegas,Rate per 1000,4.9,3.9,5.7,5.3,3.7,4.3,3.5,5.6,...,3.30,3.2,2.4,3.7,3.2,4.2,4.6,5.1,4.3,4.1
22,Long Beach,Rate per 1000,6.1,6.6,4.6,4.3,7.0,4.3,4.4,4.6,...,6.20,4.2,4.8,4.3,3.2,3.7,5.3,3.9,NaN,NaN
23,Los Angeles,Rate per 1000,6.1,4.9,5.7,5.8,5.5,5.8,5.1,4.8,...,5.00,5.2,4.9,4.6,4.9,4.5,4.3,4.2,4.4,4.0
24,Louisville,Rate per 1000,7.4,7.0,5.7,6.9,4.9,5.6,5.5,7.1,...,7.30,6.9,6.7,7.9,5.1,6.6,6.5,6.1,6.6,4.9
25,Memphis,Rate per 1000,13.3,16.1,14.9,16.7,17.3,14.7,13.3,16.0,...,14.90,11.7,10.7,11.8,10.5,10.3,9.9,10.1,11.1,10.0
26,Mesa,Rate per 1000,7.6,7.2,5.2,5.2,6.1,6.6,6.0,5.7,...,5.50,5.2,5.3,4.8,6.7,6.4,5.8,5.3,6.8,6.0
27,Miami,Rate per 1000,5.2,5.4,4.9,4.7,5.1,4.3,7.9,3.8,...,5.30,4.7,5.0,4.8,5.2,5.5,5.8,6.6,5.2,4.5
28,Milwaukee,Rate per 1000,10.5,11.4,11.5,12.1,11.4,11.9,11.1,11.9,...,11.10,9.4,9.3,9.6,11.3,8.5,9.5,9.4,12.3,10.8
29,Minneapolis,Rate per 1000,7.9,6.2,5.6,6.7,5.5,6.9,5.8,6.9,...,4.70,6.8,6.5,5.3,7.4,7.2,7.2,7.0,5.8,6.5
30,Nashville-Davidson,Rate per 1000,9.2,10.2,8.7,10.2,7.4,6.3,8.1,9.3,...,7.80,7.8,7.6,7.0,7.6,6.5,7.1,7.3,7.0,6.7
31,New York City,Rate per 1000,6.7,6.4,5.6,5.9,6.2,6.1,5.6,5.7,...,5.00,4.6,4.5,4.6,4.2,4.0,4.1,3.8,4.2,3.5
32,Oakland,Rate per 1000,6.5,5.9,7.8,5.4,6.5,6.2,6.8,5.1,...,5.70,6.5,5.0,6.4,5.7,6.1,5.2,4.5,3.7,4.7
33,Oklahoma City,Rate per 1000,9.3,12.6,8.9,8.7,10.3,10.6,9.3,7.0,...,11.00,8.1,7.2,8.2,7.9,7.0,7.4,8.9,7.4,8.1
34,Omaha,Rate per 1000,7.9,8.9,7.5,9.8,7.3,6.2,6.5,7.9,...,6.00,6.5,6.2,4.4,7.8,5.2,7.0,7.4,7.2,6.7
35,Philadelphia,Rate per 1000,12.2,10.5,10.5,10.7,10.7,11.2,12.0,12.2,...,11.10,10.5,9.5,10.0,9.3,7.3,8.0,8.5,8.3,8.1
36,Phoenix,Rate per 1000,8.0,6.7,7.9,6.6,6.8,7.2,6.7,6.8,...,6.90,7.0,7.5,6.4,5.6,6.7,5.4,6.5,5.9,5.7
37,Portland,Rate per 1000,5.2,5.9,3.2,4.5,3.9,5.3,5.9,5.8,...,5.20,5.4,4.3,4.8,4.4,5.1,5.1,3.7,4.1,3.3
38,Sacramento,Rate per 1000,6.5,6.6,7.2,7.1,5.9,5.7,5.9,6.2,...,7.00,5.2,6.3,6.0,5.5,5.2,5.7,4.8,5.5,5.9
39,San Antonio,Rate per 1000,6.5,4.9,5.7,7.3,7.5,6.3,6.6,6.5,...,5.80,6.7,5.1,7.0,6.5,5.4,6.8,6.7,6.8,7.3
40,San Diego,Rate per 1000,5.4,6.6,6.2,4.2,4.5,5.1,4.5,5.0,...,4.80,4.9,3.8,4.6,4.2,3.6,3.4,4.0,3.8,4.5
41,San Francisco,Rate per 1000,3.8,4.0,3.8,4.6,3.1,3.6,3.6,3.1,...,3.70,3.4,NaN,3.2,3.6,2.5,3.6,NaN,2.5,3.7
42,San Jose,Rate per 1000,4.7,4.8,4.2,3.6,4.0,4.5,3.8,3.9,...,4.10,3.3,3.0,3.1,4.0,3.3,3.5,3.3,3.3,4.2
43,San Juan,Rate per 1000,14.1,9.9,10.1,12.8,11.3,NaN,NaN,NaN,...,7.70,9.5,8.7,9.8,9.5,9.3,9.9,10.2,11.1,NaN
44,Seattle,Rate per 1000,6.5,4.6,4.8,4.0,5.6,5.2,4.9,3.5,...,3.90,3.5,3.7,5.4,5.0,3.7,3.3,3.6,3.3,3.9
45,Tucson,Rate per 1000,5.1,5.5,7.4,6.9,6.6,7.3,8.7,7.2,...,5.80,5.1,4.2,4.9,4.2,5.5,5.0,5.1,4.1,5.6
46,Tulsa,Rate per 1000,8.2,9.6,8.2,10.1,8.2,6.9,8.9,8.9,...,8.40,7.3,6.9,11.2,8.3,9.4,7.1,10.2,8.7,7.6
47,Virginia Beach,Rate per 1000,9.4,6.0,7.1,7.2,6.8,7.8,7.8,10.3,...,5.50,6.8,6.9,6.1,5.8,4.6,5.6,4.9,4.6,5.7
48,Wichita,Rate per 1000,NaN,NaN,NaN,NaN,NaN,8.8,10.6,7.7,...,9.30,6.9,7.3,8.8,8.9,6.1,6.6,8.3,6.9,8.1

In [184]:
# drop '-Davidson' for index 30 for consistency
inf_mor.loc[30, 'Location'] = 'Nashville'

In [185]:
# looks good, save as infant_mortality.csv
inf_mor.to_csv('../data/infant_mortality.csv')

## Making air quality data cleaning pipeline

In [192]:
air_qual_1999 = pd.read_csv('../data/conreport1999.csv')
air_qual_1999

,CBSA Code,CBSA,CO 2nd Max 1-hr,CO 2nd Max 8-hr,NO2 98th Percentile 1-hr,NO2 Mean 1-hr,Ozone 2nd Max 1-hr,Ozone 4th Max 8-hr,SO2 99th Percentile 1-hr,SO2 2nd Max 24-hr,SO2 Mean 1-hr,PM2.5 98th Percentile 24-hr,PM2.5 Weighted Mean 24-hr,PM10 2nd Max 24-hr,PM10 Mean 24-hr,Lead Max 3-Mo Avg
0,10300,"Adrian, MI",.,.,.,.,0.09,0.083,.,.,.,.,.,.,.,.
1,10420,"Akron, OH",4.7,3.1,.,.,0.12,0.098,158,65,11,42,18,68,22,.
2,10500,"Albany, GA",.,.,.,.,.,.,.,.,.,.,.,60,26,.
3,10580,"Albany-Schenectady-Troy, NY",6.4,4.2,.,.,0.11,0.092,37,16,3,.,.,.,.,.
4,10740,"Albuquerque, NM",7.5,4.6,54,16,0.1,0.076,.,.,.,.,.,93,39,.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451,49420,"Yakima, WA",8.6,4.8,.,.,.,.,.,.,.,.,.,82,25,.
452,49620,"York-Hanover, PA",5.3,2.4,64,19,0.12,0.094,83,19,7,.,.,.,.,.
453,49660,"Youngstown-Warren-Boardman, OH-PA",.,.,.,.,0.11,0.095,81,29,8,39,16.9,63,26,.
454,49700,"Yuba City, CA",6.4,4.2,69,14,0.11,0.09,.,.,.,53,15.9,155,37,.
455,49740,"Yuma, AZ",.,.,.,.,0.09,0.079,.,.,.,.,.,73,37,.

In [193]:
# manually replace some city names for consistency
air_qual_1999.loc[air_qual_1999['CBSA'].str.contains('DC')]
air_qual_1999['CBSA'] = air_qual_1999['CBSA'].str.replace('Washington-Arlington-Alexandria, DC-VA-MD-WV', 'District of Columbia')

In [195]:
air_qual_1999.loc[air_qual_1999['CBSA'].str.contains('New York')]
air_qual_1999['CBSA'] = air_qual_1999['CBSA'].str.replace('New York-Newark-Jersey City, NY-NJ-PA', 'New York City')

In [196]:
# Try to make 'CBSA' column match format of cities in infant mortality dataframe
air_qual_1999['CBSA'] = air_qual_1999['CBSA'].str.split(',', expand=True)

In [197]:
air_qual_1999.head()

,CBSA Code,CBSA,CO 2nd Max 1-hr,CO 2nd Max 8-hr,NO2 98th Percentile 1-hr,NO2 Mean 1-hr,Ozone 2nd Max 1-hr,Ozone 4th Max 8-hr,SO2 99th Percentile 1-hr,SO2 2nd Max 24-hr,SO2 Mean 1-hr,PM2.5 98th Percentile 24-hr,PM2.5 Weighted Mean 24-hr,PM10 2nd Max 24-hr,PM10 Mean 24-hr,Lead Max 3-Mo Avg
0,10300,Adrian,.,.,.,.,0.09,0.083,.,.,.,.,.,.,.,.
1,10420,Akron,4.7,3.1,.,.,0.12,0.098,158,65,11,42,18,68,22,.
2,10500,Albany,.,.,.,.,.,.,.,.,.,.,.,60,26,.
3,10580,Albany-Schenectady-Troy,6.4,4.2,.,.,0.11,0.092,37,16,3,.,.,.,.,.
4,10740,Albuquerque,7.5,4.6,54,16,0.1,0.076,.,.,.,.,.,93,39,.

In [198]:
# drop secondary cities after hyphen in CBSA column
air_qual_1999['CBSA'] = air_qual_1999['CBSA'].str.split('-', expand=True)
air_qual_1999.head(10)

,CBSA Code,CBSA,CO 2nd Max 1-hr,CO 2nd Max 8-hr,NO2 98th Percentile 1-hr,NO2 Mean 1-hr,Ozone 2nd Max 1-hr,Ozone 4th Max 8-hr,SO2 99th Percentile 1-hr,SO2 2nd Max 24-hr,SO2 Mean 1-hr,PM2.5 98th Percentile 24-hr,PM2.5 Weighted Mean 24-hr,PM10 2nd Max 24-hr,PM10 Mean 24-hr,Lead Max 3-Mo Avg
0,10300,Adrian,.,.,.,.,0.09,0.083,.,.,.,.,.,.,.,.
1,10420,Akron,4.7,3.1,.,.,0.12,0.098,158,65,11,42,18,68,22,.
2,10500,Albany,.,.,.,.,.,.,.,.,.,.,.,60,26,.
3,10580,Albany,6.4,4.2,.,.,0.11,0.092,37,16,3,.,.,.,.,.
4,10740,Albuquerque,7.5,4.6,54,16,0.1,0.076,.,.,.,.,.,93,39,.
5,10780,Alexandria,.,.,.,.,0.09,0.083,.,.,.,31,14.3,.,.,.
6,10900,Allentown,5.5,3.2,56,17,0.13,0.107,62,30,9,.,.,.,.,.
7,11020,Altoona,2.6,1.6,49,13,0.11,0.091,71,30,7,.,.,.,.,.
8,11140,Americus,.,.,.,.,0.1,0.084,.,.,.,.,.,.,.,.
9,11180,Ames,.,.,.,.,0.08,0.072,.,.,.,.,.,.,.,.

In [201]:
# get cities to research further
cities_not_in_air_qual = []
for city in inf_mor['Location']:
    if city not in air_qual_1999['CBSA'].unique():
        cities_not_in_air_qual.append(city)
cities_not_in_air_qual

['Fort Worth', 'Long Beach', 'Louisville', 'Mesa', 'Oakland']

In [202]:
# All cities except Lousville encompassed in data from neighboring cities; fix Louisville:
air_qual_1999.loc[air_qual_1999['CBSA'].str.contains('Louisville')]

,CBSA Code,CBSA,CO 2nd Max 1-hr,CO 2nd Max 8-hr,NO2 98th Percentile 1-hr,NO2 Mean 1-hr,Ozone 2nd Max 1-hr,Ozone 4th Max 8-hr,SO2 99th Percentile 1-hr,SO2 2nd Max 24-hr,SO2 Mean 1-hr,PM2.5 98th Percentile 24-hr,PM2.5 Weighted Mean 24-hr,PM10 2nd Max 24-hr,PM10 Mean 24-hr,Lead Max 3-Mo Avg
241,31140,Louisville/Jefferson County,9.1,4.8,57,14,0.12,0.103,149,32,7,40,17.5,60,29,.

In [203]:
air_qual_1999['CBSA'] = air_qual_1999['CBSA'].str.split('/', expand=True)

In [204]:
# try again
cities_not_in_air_qual = []
for city in inf_mor['Location']:
    if city not in air_qual_1999['CBSA'].unique():
        cities_not_in_air_qual.append(city)
cities_not_in_air_qual

['Fort Worth', 'Long Beach', 'Mesa', 'Oakland']

In [207]:
# drop these cities from inf_mor since data is found elsewhere
inf_mor = inf_mor.loc[~(inf_mor['Location'].isin(cities_not_in_air_qual))]
inf_mor.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45 entries, 0 to 48
Data columns (total 22 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Location     45 non-null     object
 1   Data Type_x  45 non-null     object
 2   1999         44 non-null     float64
 3   2000         44 non-null     float64
 4   2001         44 non-null     float64
 5   2002         44 non-null     float64
 6   2003         44 non-null     float64
 7   2004         43 non-null     float64
 8   2005         44 non-null     float64
 9   2006         44 non-null     float64
 10  2007         1 non-null      float64
 11  2008         1 non-null      float64
 12  2009         45 non-null     float64
 13  2010         45 non-null     float64
 14  2011         44 non-null     float64
 15  2012         45 non-null     float64
 16  2013         45 non-null     float64
 17  2014         45 non-null     float64
 18  2015         45 non-null     float64
 19  2016         44 non-null     float64
 20  2017         45 non-null     float64
 21  2018         44 non-null     float64
dtypes: float64(20), object(2)
memory usage: 8.1+ KB

In [208]:
# rewrite inf_mor to csv
inf_mor.to_csv('../data/infant_mortality.csv')

In [213]:
# drop all rows in air_qual that do not exist in infant mortality dataframe:
cities = list(inf_mor['Location'])
print(len(cities))
air_qual_1999 = air_qual_1999.loc[air_qual_1999['CBSA'].isin(cities)]
air_qual_1999

45

,CBSA Code,CBSA,CO 2nd Max 1-hr,CO 2nd Max 8-hr,NO2 98th Percentile 1-hr,NO2 Mean 1-hr,Ozone 2nd Max 1-hr,Ozone 4th Max 8-hr,SO2 99th Percentile 1-hr,SO2 2nd Max 24-hr,SO2 Mean 1-hr,PM2.5 98th Percentile 24-hr,PM2.5 Weighted Mean 24-hr,PM10 2nd Max 24-hr,PM10 Mean 24-hr,Lead Max 3-Mo Avg
4,10740,Albuquerque,7.5,4.6,54,16,0.1,0.076,.,.,.,.,.,93,39,.
19,12060,Atlanta,6.3,4.1,87,24,0.16,0.124,90,23,5,48,23,72,35,.
23,12420,Austin,2.1,1.2,.,6,0.11,0.099,.,.,.,.,.,.,.,.
25,12580,Baltimore,10.2,5.6,70,24,0.15,0.113,79,20,6,.,.,61,32,.
46,14460,Boston,8.4,4.2,77,30,0.12,0.093,93,40,8,47,15.3,65,30,.
75,16740,Charlotte,7.1,4.3,.,18,0.13,0.107,.,.,.,38,17.6,60,30,.
78,16980,Chicago,6.4,4.9,83,32,0.13,0.102,138,44,9,54,21.8,165,40,.
85,17420,Cleveland,.,.,54,15,.,.,115,34,8,.,.,51,27,.
86,17460,Cleveland,6.8,3.9,68,25,0.12,0.103,201,62,11,38,15.3,106,42,.
90,17820,Colorado Springs,12.6,5.2,88,19,0.08,0.065,56,20,4,.,.,79,22,.
92,17980,Columbus,.,.,.,.,0.11,0.097,37,10,2,.,.,45,24,.
93,18140,Columbus,8.5,2.5,.,.,0.14,0.103,44,15,4,40,17.7,76,27,.
100,19100,Dallas,4.8,3.2,76,21,0.15,0.112,149,33,4,.,.,57,32,.
107,19740,Denver,12.1,5.2,78,19,0.11,0.081,81,12,3,.,.,141,36,.
110,19820,Detroit,6,4.4,.,18,0.12,0.096,172,53,9,44,13.2,96,36,.
130,21340,El Paso,14.4,8.2,74,28,0.11,0.073,56,16,2,.,.,209,66,.
150,23420,Fresno,10,7.6,93,24,0.15,0.105,.,.,.,97,23.4,127,46,.
187,26420,Houston,6.3,4.1,74,24,0.2,0.124,99,40,7,.,.,116,44,.
191,26900,Indianapolis,4.8,2.6,.,18,0.11,0.096,115,24,7,.,.,53,27,.
197,27260,Jacksonville,6.3,4.1,53,16,0.1,0.08,126,36,4,.,.,58,28,.
198,27340,Jacksonville,.,.,.,.,.,.,.,.,.,36,12.7,.,.,.
208,28140,Kansas City,9.5,4.7,62,15,0.12,0.084,29,11,2,30,14.1,118,40,.
227,29820,Las Vegas,10.2,8.2,85,27,0.1,0.084,14,7,1,26,10.3,281,56,.
240,31080,Los Angeles,16,11.1,139,51,0.14,0.095,48,19,4,53,24.3,119,56,.
241,31140,Louisville,9.1,4.8,57,14,0.12,0.103,149,32,7,40,17.5,60,29,.
256,32820,Memphis,7.6,5.2,72,25,0.13,0.104,81,28,6,35,15.9,64,27,.
259,33100,Miami,7.9,5.4,67,17,0.11,0.079,79,15,3,25,9.3,44,24,.
262,33340,Milwaukee,3.5,2.2,67,22,0.12,0.097,95,24,4,40,15,60,27,.
263,33460,Minneapolis,7.6,5.2,63,22,0.1,0.078,38,17,2,.,.,88,35,.
283,34980,Nashville,7.6,5.4,97,18,0.12,0.101,182,35,5,51,18.8,74,32,.
289,35620,New York City,10,6.6,100,42,0.15,0.11,79,45,13,39,13.7,73,35,.
296,36420,Oklahoma City,6.5,4.3,63,14,0.1,0.084,12,9,3,.,.,.,.,.
298,36540,Omaha,12.4,8.8,.,.,0.09,0.08,.,.,.,.,.,102,43,.
312,37980,Philadelphia,7.4,4.9,68,32,0.15,0.112,170,49,10,35,14.3,51,22,.
313,38060,Phoenix,13.5,8.1,172,40,0.12,0.091,.,.,.,30,12.2,115,59,.
322,38860,Portland,.,.,.,.,0.12,0.089,.,.,.,.,.,43,21,.
323,38900,Portland,12.9,6.7,.,.,0.09,0.072,.,.,.,35,8.8,62,22,.
352,40900,Sacramento,7.3,6.2,81,21,0.14,0.106,18,12,4,40,13.4,144,34,.
361,41700,San Antonio,6.3,4.2,.,25,0.11,0.091,.,.,.,.,.,.,.,.
362,41740,San Diego,9.2,4.9,100,26,0.11,0.092,63,16,3,38,16.4,112,52,.
364,41860,San Francisco,7.8,4.5,72,22,0.14,0.093,56,20,3,.,.,94,26,.
365,41940,San Jose,8.8,6.2,93,26,0.12,0.082,.,.,.,60,16.3,93,28,.
366,41980,San Juan,12.8,9.9,.,.,.,.,.,.,.,.,.,133,50,.
375,42660,Seattle,15.6,6.6,56,19,0.09,0.072,.,.,.,46,11.5,50,25,.
411,46060,Tucson,7.8,3.8,59,19,0.09,0.073,12,5,2,20,8.8,80,43,.
412,46140,Tulsa,5.6,3.5,62,17,0.12,0.091,169,83,11,.,.,.,.,.
425,47260,Virginia Beach,9.2,4.6,60,17,0.14,0.097,92,22,7,.,.,50,19,.
433,47900,District of Columbia,7.5,5.6,74,25,0.14,0.107,150,26,9,.,.,57,23,.
442,48620,Wichita,8.6,4.6,.,.,0.1,0.079,.,.,.,28,11.9,85,30,.

In [214]:
# Investigate duplicates manually
cbsa_codes_to_drop = [17420, 17980, 27340, 38860]
air_qual_1999 = air_qual_1999.loc[~(air_qual_1999['CBSA Code'].isin(cbsa_codes_to_drop))]
air_qual_1999

,CBSA Code,CBSA,CO 2nd Max 1-hr,CO 2nd Max 8-hr,NO2 98th Percentile 1-hr,NO2 Mean 1-hr,Ozone 2nd Max 1-hr,Ozone 4th Max 8-hr,SO2 99th Percentile 1-hr,SO2 2nd Max 24-hr,SO2 Mean 1-hr,PM2.5 98th Percentile 24-hr,PM2.5 Weighted Mean 24-hr,PM10 2nd Max 24-hr,PM10 Mean 24-hr,Lead Max 3-Mo Avg
4,10740,Albuquerque,7.5,4.6,54,16,0.1,0.076,.,.,.,.,.,93,39,.
19,12060,Atlanta,6.3,4.1,87,24,0.16,0.124,90,23,5,48,23,72,35,.
23,12420,Austin,2.1,1.2,.,6,0.11,0.099,.,.,.,.,.,.,.,.
25,12580,Baltimore,10.2,5.6,70,24,0.15,0.113,79,20,6,.,.,61,32,.
46,14460,Boston,8.4,4.2,77,30,0.12,0.093,93,40,8,47,15.3,65,30,.
75,16740,Charlotte,7.1,4.3,.,18,0.13,0.107,.,.,.,38,17.6,60,30,.
78,16980,Chicago,6.4,4.9,83,32,0.13,0.102,138,44,9,54,21.8,165,40,.
86,17460,Cleveland,6.8,3.9,68,25,0.12,0.103,201,62,11,38,15.3,106,42,.
90,17820,Colorado Springs,12.6,5.2,88,19,0.08,0.065,56,20,4,.,.,79,22,.
93,18140,Columbus,8.5,2.5,.,.,0.14,0.103,44,15,4,40,17.7,76,27,.
100,19100,Dallas,4.8,3.2,76,21,0.15,0.112,149,33,4,.,.,57,32,.
107,19740,Denver,12.1,5.2,78,19,0.11,0.081,81,12,3,.,.,141,36,.
110,19820,Detroit,6,4.4,.,18,0.12,0.096,172,53,9,44,13.2,96,36,.
130,21340,El Paso,14.4,8.2,74,28,0.11,0.073,56,16,2,.,.,209,66,.
150,23420,Fresno,10,7.6,93,24,0.15,0.105,.,.,.,97,23.4,127,46,.
187,26420,Houston,6.3,4.1,74,24,0.2,0.124,99,40,7,.,.,116,44,.
191,26900,Indianapolis,4.8,2.6,.,18,0.11,0.096,115,24,7,.,.,53,27,.
197,27260,Jacksonville,6.3,4.1,53,16,0.1,0.08,126,36,4,.,.,58,28,.
208,28140,Kansas City,9.5,4.7,62,15,0.12,0.084,29,11,2,30,14.1,118,40,.
227,29820,Las Vegas,10.2,8.2,85,27,0.1,0.084,14,7,1,26,10.3,281,56,.
240,31080,Los Angeles,16,11.1,139,51,0.14,0.095,48,19,4,53,24.3,119,56,.
241,31140,Louisville,9.1,4.8,57,14,0.12,0.103,149,32,7,40,17.5,60,29,.
256,32820,Memphis,7.6,5.2,72,25,0.13,0.104,81,28,6,35,15.9,64,27,.
259,33100,Miami,7.9,5.4,67,17,0.11,0.079,79,15,3,25,9.3,44,24,.
262,33340,Milwaukee,3.5,2.2,67,22,0.12,0.097,95,24,4,40,15,60,27,.
263,33460,Minneapolis,7.6,5.2,63,22,0.1,0.078,38,17,2,.,.,88,35,.
283,34980,Nashville,7.6,5.4,97,18,0.12,0.101,182,35,5,51,18.8,74,32,.
289,35620,New York City,10,6.6,100,42,0.15,0.11,79,45,13,39,13.7,73,35,.
296,36420,Oklahoma City,6.5,4.3,63,14,0.1,0.084,12,9,3,.,.,.,.,.
298,36540,Omaha,12.4,8.8,.,.,0.09,0.08,.,.,.,.,.,102,43,.
312,37980,Philadelphia,7.4,4.9,68,32,0.15,0.112,170,49,10,35,14.3,51,22,.
313,38060,Phoenix,13.5,8.1,172,40,0.12,0.091,.,.,.,30,12.2,115,59,.
323,38900,Portland,12.9,6.7,.,.,0.09,0.072,.,.,.,35,8.8,62,22,.
352,40900,Sacramento,7.3,6.2,81,21,0.14,0.106,18,12,4,40,13.4,144,34,.
361,41700,San Antonio,6.3,4.2,.,25,0.11,0.091,.,.,.,.,.,.,.,.
362,41740,San Diego,9.2,4.9,100,26,0.11,0.092,63,16,3,38,16.4,112,52,.
364,41860,San Francisco,7.8,4.5,72,22,0.14,0.093,56,20,3,.,.,94,26,.
365,41940,San Jose,8.8,6.2,93,26,0.12,0.082,.,.,.,60,16.3,93,28,.
366,41980,San Juan,12.8,9.9,.,.,.,.,.,.,.,.,.,133,50,.
375,42660,Seattle,15.6,6.6,56,19,0.09,0.072,.,.,.,46,11.5,50,25,.
411,46060,Tucson,7.8,3.8,59,19,0.09,0.073,12,5,2,20,8.8,80,43,.
412,46140,Tulsa,5.6,3.5,62,17,0.12,0.091,169,83,11,.,.,.,.,.
425,47260,Virginia Beach,9.2,4.6,60,17,0.14,0.097,92,22,7,.,.,50,19,.
433,47900,District of Columbia,7.5,5.6,74,25,0.14,0.107,150,26,9,.,.,57,23,.
442,48620,Wichita,8.6,4.6,.,.,0.1,0.079,.,.,.,28,11.9,85,30,.

In [215]:
air_qual_1999.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45 entries, 4 to 442
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   CBSA Code                    45 non-null     int64
 1   CBSA                         45 non-null     object
 2   CO 2nd Max 1-hr              45 non-null     object
 3   CO 2nd Max 8-hr              45 non-null     object
 4   NO2 98th Percentile 1-hr     45 non-null     object
 5   NO2 Mean 1-hr                45 non-null     object
 6   Ozone 2nd Max 1-hr           45 non-null     object
 7   Ozone 4th Max 8-hr           45 non-null     object
 8   SO2 99th Percentile 1-hr     45 non-null     object
 9   SO2 2nd Max 24-hr            45 non-null     object
 10  SO2 Mean 1-hr                45 non-null     object
 11  PM2.5 98th Percentile 24-hr  45 non-null     object
 12  PM2.5 Weighted Mean 24-hr    45 non-null     object
 13  PM10 2nd Max 24-hr           45 non-null     object
 14  PM10 Mean 24-hr              45 non-null     object
 15  Lead Max 3-Mo Avg            45 non-null     object
dtypes: int64(1), object(15)
memory usage: 6.0+ KB

In [217]:
# check for dtype where float appears to be entered
print(air_qual_1999.loc[4, 'CO 2nd Max 1-hr'])
type(air_qual_1999.loc[4, 'CO 2nd Max 1-hr'])

7.5

str

In [230]:
print(air_qual_1999.loc[4, 'SO2 Mean 1-hr'])
type(air_qual_1999.loc[4, 'SO2 Mean 1-hr'])

nan

numpy.float64

In [232]:
air_columns

Index(['CO 2nd Max 1-hr', 'CO 2nd Max 8-hr', 'NO2 98th Percentile 1-hr',
       'NO2 Mean 1-hr', 'Ozone 2nd Max 1-hr', 'Ozone 4th Max 8-hr',
       'SO2 99th Percentile 1-hr', 'SO2 2nd Max 24-hr', 'SO2 Mean 1-hr',
       'PM2.5 98th Percentile 24-hr', 'PM2.5 Weighted Mean 24-hr',
       'PM10 2nd Max 24-hr', 'PM10 Mean 24-hr', 'Lead Max 3-Mo Avg'],
      dtype='object')